// Code generated by mkcgo. DO NOT EDIT.

//go:build go1.24 && !cmd_go_bootstrap

package openssl

/*
#cgo noescape EVP_CipherUpdate
#cgo nocallback EVP_CipherUpdate
#cgo noescape EVP_DecryptFinal_ex
#cgo nocallback EVP_DecryptFinal_ex
#cgo noescape EVP_DecryptUpdate
#cgo nocallback EVP_DecryptUpdate
#cgo noescape EVP_Digest
#cgo nocallback EVP_Digest
#cgo noescape EVP_DigestSign
#cgo nocallback EVP_DigestSign
#cgo noescape EVP_DigestUpdate
#cgo nocallback EVP_DigestUpdate
#cgo noescape EVP_EncryptFinal_ex
#cgo nocallback EVP_EncryptFinal_ex
#cgo noescape EVP_EncryptUpdate
#cgo nocallback EVP_EncryptUpdate
#cgo noescape EVP_PKEY_derive
#cgo nocallback EVP_PKEY_derive
#cgo noescape EVP_PKEY_get_raw_private_key
#cgo nocallback EVP_PKEY_get_raw_private_key
#cgo noescape EVP_PKEY_get_raw_public_key
#cgo nocallback EVP_PKEY_get_raw_public_key
#cgo noescape RAND_bytes
#cgo nocallback RAND_bytes
*/
import "C"
