// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by mkcgo. DO NOT EDIT.

//go:build !cgo && unix

#include "textflag.h"

#define _GOPTRSIZE 8
TEXT _mkcgo_dlclose_trampoline<>(SB), NOSPLIT, $0-0
	CALL _mkcgo_dlclose(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

GLOBL ·_mkcgo_dlclose_trampoline_addr(SB), RODATA, $_GOPTRSIZE
DATA ·_mkcgo_dlclose_trampoline_addr(SB)/_GOPTRSIZE, $_mkcgo_dlclose_trampoline<>(SB)

TEXT _mkcgo_dlerror_trampoline<>(SB), NOSPLIT, $0-0
	CALL _mkcgo_dlerror(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

GLOBL ·_mkcgo_dlerror_trampoline_addr(SB), RODATA, $_GOPTRSIZE
DATA ·_mkcgo_dlerror_trampoline_addr(SB)/_GOPTRSIZE, $_mkcgo_dlerror_trampoline<>(SB)

TEXT _mkcgo_dlopen_trampoline<>(SB), NOSPLIT, $0-0
	CALL _mkcgo_dlopen(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

GLOBL ·_mkcgo_dlopen_trampoline_addr(SB), RODATA, $_GOPTRSIZE
DATA ·_mkcgo_dlopen_trampoline_addr(SB)/_GOPTRSIZE, $_mkcgo_dlopen_trampoline<>(SB)

TEXT _mkcgo_dlsym_trampoline<>(SB), NOSPLIT, $0-0
	CALL _mkcgo_dlsym(SB)
	// The NOP is the TOC restore slot. The linker rewrites it to
	// MOVD 24(R1), R2 when linking PIC code.
	WORD $0x60000000
	RET

GLOBL ·_mkcgo_dlsym_trampoline_addr(SB), RODATA, $_GOPTRSIZE
DATA ·_mkcgo_dlsym_trampoline_addr(SB)/_GOPTRSIZE, $_mkcgo_dlsym_trampoline<>(SB)
