// Code generated by mkcgo. DO NOT EDIT.

package ossl

/*
#cgo CFLAGS: -Wno-attributes
#cgo unix LDFLAGS: -ldl

#include "zossl.h"
*/
import "C"
import "unsafe"

type BIGNUM_PTR = C._BIGNUM_PTR
type BIO_METHOD_PTR = C._BIO_METHOD_PTR
type BIO_PTR = C._BIO_PTR
type BN_CTX_PTR = C._BN_CTX_PTR
type DSA_PTR = C._DSA_PTR
type EC_GROUP_PTR = C._EC_GROUP_PTR
type EC_KEY_PTR = C._EC_KEY_PTR
type EC_POINT_PTR = C._EC_POINT_PTR
type ENGINE_PTR = C._ENGINE_PTR
type EVP_CIPHER_CTX_PTR = C._EVP_CIPHER_CTX_PTR
type EVP_CIPHER_PTR = C._EVP_CIPHER_PTR
type EVP_KDF_CTX_PTR = C._EVP_KDF_CTX_PTR
type EVP_KDF_PTR = C._EVP_KDF_PTR
type EVP_KEYMGMT_PTR = C._EVP_KEYMGMT_PTR
type EVP_MAC_CTX_PTR = C._EVP_MAC_CTX_PTR
type EVP_MAC_PTR = C._EVP_MAC_PTR
type EVP_MD_CTX_PTR = C._EVP_MD_CTX_PTR
type EVP_MD_PTR = C._EVP_MD_PTR
type EVP_PKEY_CTX_PTR = C._EVP_PKEY_CTX_PTR
type EVP_PKEY_PTR = C._EVP_PKEY_PTR
type EVP_SIGNATURE_PTR = C._EVP_SIGNATURE_PTR
type HMAC_CTX_PTR = C._HMAC_CTX_PTR
type OPENSSL_INIT_SETTINGS_PTR = C._OPENSSL_INIT_SETTINGS_PTR
type OSSL_LIB_CTX_PTR = C._OSSL_LIB_CTX_PTR
type OSSL_PARAM_BLD_PTR = C._OSSL_PARAM_BLD_PTR
type OSSL_PARAM_PTR = C._OSSL_PARAM_PTR
type OSSL_PROVIDER_PTR = C._OSSL_PROVIDER_PTR
type RSA_PTR = C._RSA_PTR
type Point_conversion_form_t = C.point_conversion_form_t

func MkcgoLoad_(handle unsafe.Pointer) {
	C.__mkcgo_load_(handle)
}

func MkcgoUnload_() {
	C.__mkcgo_unload_()
}

func MkcgoLoad_111(handle unsafe.Pointer) {
	C.__mkcgo_load_111(handle)
}

func MkcgoUnload_111() {
	C.__mkcgo_unload_111()
}

func MkcgoLoad_3(handle unsafe.Pointer) {
	C.__mkcgo_load_3(handle)
}

func MkcgoUnload_3() {
	C.__mkcgo_unload_3()
}

func MkcgoLoad_33(handle unsafe.Pointer) {
	C.__mkcgo_load_33(handle)
}

func MkcgoUnload_33() {
	C.__mkcgo_unload_33()
}

func MkcgoLoad_init_1(handle unsafe.Pointer) {
	C.__mkcgo_load_init_1(handle)
}

func MkcgoUnload_init_1() {
	C.__mkcgo_unload_init_1()
}

func MkcgoLoad_init_3(handle unsafe.Pointer) {
	C.__mkcgo_load_init_3(handle)
}

func MkcgoUnload_init_3() {
	C.__mkcgo_unload_init_3()
}

func MkcgoLoad_legacy_1(handle unsafe.Pointer) {
	C.__mkcgo_load_legacy_1(handle)
}

func MkcgoUnload_legacy_1() {
	C.__mkcgo_unload_legacy_1()
}

func MkcgoLoad_version(handle unsafe.Pointer) {
	C.__mkcgo_load_version(handle)
}

func MkcgoUnload_version() {
	C.__mkcgo_unload_version()
}

//go:nosplit
func mkcgoNoEscape(p *C.uintptr_t) *C.uintptr_t {
	x := uintptr(unsafe.Pointer(p))
	return (*C.uintptr_t)(unsafe.Pointer(x ^ 0))
}

func BIO_ctrl(bp BIO_PTR, cmd int32, larg int64, parg unsafe.Pointer) int64 {
	return int64(C._mkcgo_BIO_ctrl(bp, C.int(cmd), C.long(larg), parg))
}

func BIO_free(a BIO_PTR) int32 {
	return int32(C._mkcgo_BIO_free(a))
}

func BIO_new(__type BIO_METHOD_PTR) (BIO_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_BIO_new(__type, mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("BIO_new", uintptr(_err))
}

func BIO_s_mem() BIO_METHOD_PTR {
	return C._mkcgo_BIO_s_mem()
}

func BN_bin2bn(arg0 *byte, arg1 int32, arg2 BIGNUM_PTR) (BIGNUM_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_BN_bin2bn((*C.uchar)(unsafe.Pointer(arg0)), C.int(arg1), arg2, mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("BN_bin2bn", uintptr(_err))
}

func BN_bn2binpad(a BIGNUM_PTR, to *byte, tolen int32) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_BN_bn2binpad(a, (*C.uchar)(unsafe.Pointer(to)), C.int(tolen), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("BN_bn2binpad", uintptr(_err))
}

func BN_bn2lebinpad(a BIGNUM_PTR, to *byte, tolen int32) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_BN_bn2lebinpad(a, (*C.uchar)(unsafe.Pointer(to)), C.int(tolen), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("BN_bn2lebinpad", uintptr(_err))
}

func BN_clear(arg0 BIGNUM_PTR) {
	C._mkcgo_BN_clear(arg0)
}

func BN_clear_free(arg0 BIGNUM_PTR) {
	C._mkcgo_BN_clear_free(arg0)
}

func BN_free(arg0 BIGNUM_PTR) {
	C._mkcgo_BN_free(arg0)
}

func BN_lebin2bn(s *byte, len int32, ret BIGNUM_PTR) (BIGNUM_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_BN_lebin2bn((*C.uchar)(unsafe.Pointer(s)), C.int(len), ret, mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("BN_lebin2bn", uintptr(_err))
}

func BN_new() (BIGNUM_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_BN_new(mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("BN_new", uintptr(_err))
}

func BN_num_bits(arg0 BIGNUM_PTR) int32 {
	return int32(C._mkcgo_BN_num_bits(arg0))
}

func CRYPTO_free(str unsafe.Pointer, file *byte, line int32) {
	C._mkcgo_CRYPTO_free(str, (*C.char)(unsafe.Pointer(file)), C.int(line))
}

func CRYPTO_malloc(num int, file *byte, line int32) (unsafe.Pointer, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_CRYPTO_malloc(C.size_t(num), (*C.char)(unsafe.Pointer(file)), C.int(line), mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("CRYPTO_malloc", uintptr(_err))
}

func DSA_free(r DSA_PTR) {
	C._mkcgo_DSA_free(r)
}

func DSA_generate_key(a DSA_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_DSA_generate_key(a, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("DSA_generate_key", uintptr(_err))
}

func DSA_get0_key(d DSA_PTR, pub_key *BIGNUM_PTR, priv_key *BIGNUM_PTR) {
	C._mkcgo_DSA_get0_key(d, pub_key, priv_key)
}

func DSA_get0_pqg(d DSA_PTR, p *BIGNUM_PTR, q *BIGNUM_PTR, g *BIGNUM_PTR) {
	C._mkcgo_DSA_get0_pqg(d, p, q, g)
}

func DSA_new() (DSA_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_DSA_new(mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("DSA_new", uintptr(_err))
}

func DSA_set0_key(d DSA_PTR, pub_key BIGNUM_PTR, priv_key BIGNUM_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_DSA_set0_key(d, pub_key, priv_key, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("DSA_set0_key", uintptr(_err))
}

func DSA_set0_pqg(d DSA_PTR, p BIGNUM_PTR, q BIGNUM_PTR, g BIGNUM_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_DSA_set0_pqg(d, p, q, g, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("DSA_set0_pqg", uintptr(_err))
}

func EC_GROUP_free(group EC_GROUP_PTR) {
	C._mkcgo_EC_GROUP_free(group)
}

func EC_GROUP_new_by_curve_name(nid int32) (EC_GROUP_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EC_GROUP_new_by_curve_name(C.int(nid), mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EC_GROUP_new_by_curve_name", uintptr(_err))
}

func EC_KEY_check_key(key EC_KEY_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EC_KEY_check_key(key, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EC_KEY_check_key", uintptr(_err))
}

func EC_KEY_free(arg0 EC_KEY_PTR) {
	C._mkcgo_EC_KEY_free(arg0)
}

func EC_KEY_get0_group(arg0 EC_KEY_PTR) EC_GROUP_PTR {
	return C._mkcgo_EC_KEY_get0_group(arg0)
}

func EC_KEY_get0_private_key(arg0 EC_KEY_PTR) BIGNUM_PTR {
	return C._mkcgo_EC_KEY_get0_private_key(arg0)
}

func EC_KEY_get0_public_key(arg0 EC_KEY_PTR) EC_POINT_PTR {
	return C._mkcgo_EC_KEY_get0_public_key(arg0)
}

func EC_KEY_new_by_curve_name(arg0 int32) (EC_KEY_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EC_KEY_new_by_curve_name(C.int(arg0), mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EC_KEY_new_by_curve_name", uintptr(_err))
}

func EC_KEY_set_private_key(arg0 EC_KEY_PTR, arg1 BIGNUM_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EC_KEY_set_private_key(arg0, arg1, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EC_KEY_set_private_key", uintptr(_err))
}

func EC_KEY_set_public_key(key EC_KEY_PTR, pub EC_POINT_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EC_KEY_set_public_key(key, pub, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EC_KEY_set_public_key", uintptr(_err))
}

func EC_KEY_set_public_key_affine_coordinates(key EC_KEY_PTR, x BIGNUM_PTR, y BIGNUM_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EC_KEY_set_public_key_affine_coordinates(key, x, y, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EC_KEY_set_public_key_affine_coordinates", uintptr(_err))
}

func EC_POINT_free(arg0 EC_POINT_PTR) {
	C._mkcgo_EC_POINT_free(arg0)
}

func EC_POINT_get_affine_coordinates_GFp(arg0 EC_GROUP_PTR, arg1 EC_POINT_PTR, arg2 BIGNUM_PTR, arg3 BIGNUM_PTR, arg4 BN_CTX_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EC_POINT_get_affine_coordinates_GFp(arg0, arg1, arg2, arg3, arg4, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EC_POINT_get_affine_coordinates_GFp", uintptr(_err))
}

func EC_POINT_mul(group EC_GROUP_PTR, r EC_POINT_PTR, n BIGNUM_PTR, q EC_POINT_PTR, m BIGNUM_PTR, ctx BN_CTX_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EC_POINT_mul(group, r, n, q, m, ctx, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EC_POINT_mul", uintptr(_err))
}

func EC_POINT_new(arg0 EC_GROUP_PTR) (EC_POINT_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EC_POINT_new(arg0, mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EC_POINT_new", uintptr(_err))
}

func EC_POINT_oct2point(group EC_GROUP_PTR, p EC_POINT_PTR, buf *byte, len int, ctx BN_CTX_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EC_POINT_oct2point(group, p, (*C.uchar)(unsafe.Pointer(buf)), C.size_t(len), ctx, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EC_POINT_oct2point", uintptr(_err))
}

func EC_POINT_point2oct(group EC_GROUP_PTR, p EC_POINT_PTR, form Point_conversion_form_t, buf *byte, len int, ctx BN_CTX_PTR) (int, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EC_POINT_point2oct(group, p, form, (*C.uchar)(unsafe.Pointer(buf)), C.size_t(len), ctx, mkcgoNoEscape(&_err))
	return int(_ret), newMkcgoErr("EC_POINT_point2oct", uintptr(_err))
}

func EC_POINT_set_affine_coordinates(arg0 EC_GROUP_PTR, arg1 EC_POINT_PTR, arg2 BIGNUM_PTR, arg3 BIGNUM_PTR, arg4 BN_CTX_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EC_POINT_set_affine_coordinates(arg0, arg1, arg2, arg3, arg4, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EC_POINT_set_affine_coordinates", uintptr(_err))
}

func ERR_peek_error() uint64 {
	return uint64(C._mkcgo_ERR_peek_error())
}

func ERR_print_errors(bp BIO_PTR) {
	C._mkcgo_ERR_print_errors(bp)
}

func EVP_CIPHER_CTX_ctrl(ctx EVP_CIPHER_CTX_PTR, __type int32, arg int32, ptr unsafe.Pointer) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_CIPHER_CTX_ctrl(ctx, C.int(__type), C.int(arg), ptr, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_CIPHER_CTX_ctrl", uintptr(_err))
}

func EVP_CIPHER_CTX_free(arg0 EVP_CIPHER_CTX_PTR) {
	C._mkcgo_EVP_CIPHER_CTX_free(arg0)
}

func EVP_CIPHER_CTX_new() (EVP_CIPHER_CTX_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_CIPHER_CTX_new(mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_CIPHER_CTX_new", uintptr(_err))
}

func EVP_CIPHER_CTX_set_key_length(x EVP_CIPHER_CTX_PTR, keylen int32) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_CIPHER_CTX_set_key_length(x, C.int(keylen), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_CIPHER_CTX_set_key_length", uintptr(_err))
}

func EVP_CIPHER_CTX_set_padding(x EVP_CIPHER_CTX_PTR, padding int32) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_CIPHER_CTX_set_padding(x, C.int(padding), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_CIPHER_CTX_set_padding", uintptr(_err))
}

func EVP_CIPHER_fetch(ctx OSSL_LIB_CTX_PTR, algorithm *byte, properties *byte) (EVP_CIPHER_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_CIPHER_fetch(ctx, (*C.char)(unsafe.Pointer(algorithm)), (*C.char)(unsafe.Pointer(properties)), mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_CIPHER_fetch", uintptr(_err))
}

func EVP_CIPHER_get0_name(cipher EVP_CIPHER_PTR) *byte {
	return (*byte)(unsafe.Pointer(C._mkcgo_EVP_CIPHER_get0_name(cipher)))
}

func EVP_CIPHER_get_block_size(cipher EVP_CIPHER_PTR) int32 {
	return int32(C._mkcgo_EVP_CIPHER_get_block_size(cipher))
}

func EVP_CipherInit_ex(ctx EVP_CIPHER_CTX_PTR, __type EVP_CIPHER_PTR, impl ENGINE_PTR, key *byte, iv *byte, enc int32) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_CipherInit_ex(ctx, __type, impl, (*C.uchar)(unsafe.Pointer(key)), (*C.uchar)(unsafe.Pointer(iv)), C.int(enc), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_CipherInit_ex", uintptr(_err))
}

func EVP_CipherUpdate(ctx EVP_CIPHER_CTX_PTR, out *byte, outl *int32, in *byte, inl int32) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_CipherUpdate(ctx, (*C.uchar)(unsafe.Pointer(out)), (*C.int)(unsafe.Pointer(outl)), (*C.uchar)(unsafe.Pointer(in)), C.int(inl), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_CipherUpdate", uintptr(_err))
}

func EVP_DecryptFinal_ex(ctx EVP_CIPHER_CTX_PTR, outm *byte, outl *int32) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_DecryptFinal_ex(ctx, (*C.uchar)(unsafe.Pointer(outm)), (*C.int)(unsafe.Pointer(outl)), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_DecryptFinal_ex", uintptr(_err))
}

func EVP_DecryptInit_ex(ctx EVP_CIPHER_CTX_PTR, __type EVP_CIPHER_PTR, impl ENGINE_PTR, key *byte, iv *byte) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_DecryptInit_ex(ctx, __type, impl, (*C.uchar)(unsafe.Pointer(key)), (*C.uchar)(unsafe.Pointer(iv)), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_DecryptInit_ex", uintptr(_err))
}

func EVP_DecryptUpdate(ctx EVP_CIPHER_CTX_PTR, out *byte, outl *int32, in *byte, inl int32) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_DecryptUpdate(ctx, (*C.uchar)(unsafe.Pointer(out)), (*C.int)(unsafe.Pointer(outl)), (*C.uchar)(unsafe.Pointer(in)), C.int(inl), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_DecryptUpdate", uintptr(_err))
}

func EVP_Digest(data []byte, md []byte, size *uint32, __type EVP_MD_PTR, impl ENGINE_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_Digest((*C.uchar)(unsafe.Pointer(unsafe.SliceData(data))), C.size_t(len(data)), (*C.uchar)(unsafe.Pointer(unsafe.SliceData(md))), (*C.uint)(unsafe.Pointer(size)), __type, impl, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_Digest", uintptr(_err))
}

func EVP_DigestFinalXOF(ctx EVP_MD_CTX_PTR, md []byte, len int) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_DigestFinalXOF(ctx, (*C.uchar)(unsafe.Pointer(unsafe.SliceData(md))), C.size_t(len), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_DigestFinalXOF", uintptr(_err))
}

func EVP_DigestFinal_ex(ctx EVP_MD_CTX_PTR, md []byte, s *uint32) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_DigestFinal_ex(ctx, (*C.uchar)(unsafe.Pointer(unsafe.SliceData(md))), (*C.uint)(unsafe.Pointer(s)), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_DigestFinal_ex", uintptr(_err))
}

func EVP_DigestInit(ctx EVP_MD_CTX_PTR, __type EVP_MD_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_DigestInit(ctx, __type, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_DigestInit", uintptr(_err))
}

func EVP_DigestInit_ex(ctx EVP_MD_CTX_PTR, __type EVP_MD_PTR, impl ENGINE_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_DigestInit_ex(ctx, __type, impl, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_DigestInit_ex", uintptr(_err))
}

func EVP_DigestSign(ctx EVP_MD_CTX_PTR, sigret *byte, siglen *int, tbs *byte, tbslen int) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_DigestSign(ctx, (*C.uchar)(unsafe.Pointer(sigret)), (*C.size_t)(unsafe.Pointer(siglen)), (*C.uchar)(unsafe.Pointer(tbs)), C.size_t(tbslen), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_DigestSign", uintptr(_err))
}

func EVP_DigestSignFinal(ctx EVP_MD_CTX_PTR, sig *byte, siglen *int) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_DigestSignFinal(ctx, (*C.uchar)(unsafe.Pointer(sig)), (*C.size_t)(unsafe.Pointer(siglen)), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_DigestSignFinal", uintptr(_err))
}

func EVP_DigestSignInit(ctx EVP_MD_CTX_PTR, pctx *EVP_PKEY_CTX_PTR, __type EVP_MD_PTR, e ENGINE_PTR, pkey EVP_PKEY_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_DigestSignInit(ctx, pctx, __type, e, pkey, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_DigestSignInit", uintptr(_err))
}

func EVP_DigestSqueeze(ctx EVP_MD_CTX_PTR, out []byte) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_DigestSqueeze(ctx, (*C.uchar)(unsafe.Pointer(unsafe.SliceData(out))), C.size_t(len(out)), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_DigestSqueeze", uintptr(_err))
}

func EVP_DigestUpdate(ctx EVP_MD_CTX_PTR, d []byte) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_DigestUpdate(ctx, (*C.uchar)(unsafe.Pointer(unsafe.SliceData(d))), C.size_t(len(d)), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_DigestUpdate", uintptr(_err))
}

func EVP_DigestVerify(ctx EVP_MD_CTX_PTR, sigret *byte, siglen int, tbs *byte, tbslen int) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_DigestVerify(ctx, (*C.uchar)(unsafe.Pointer(sigret)), C.size_t(siglen), (*C.uchar)(unsafe.Pointer(tbs)), C.size_t(tbslen), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_DigestVerify", uintptr(_err))
}

func EVP_DigestVerifyFinal(ctx EVP_MD_CTX_PTR, sig *byte, siglen int) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_DigestVerifyFinal(ctx, (*C.uchar)(unsafe.Pointer(sig)), C.size_t(siglen), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_DigestVerifyFinal", uintptr(_err))
}

func EVP_DigestVerifyInit(ctx EVP_MD_CTX_PTR, pctx *EVP_PKEY_CTX_PTR, __type EVP_MD_PTR, e ENGINE_PTR, pkey EVP_PKEY_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_DigestVerifyInit(ctx, pctx, __type, e, pkey, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_DigestVerifyInit", uintptr(_err))
}

func EVP_EncryptFinal_ex(ctx EVP_CIPHER_CTX_PTR, out *byte, outl *int32) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_EncryptFinal_ex(ctx, (*C.uchar)(unsafe.Pointer(out)), (*C.int)(unsafe.Pointer(outl)), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_EncryptFinal_ex", uintptr(_err))
}

func EVP_EncryptInit_ex(ctx EVP_CIPHER_CTX_PTR, __type EVP_CIPHER_PTR, impl ENGINE_PTR, key *byte, iv *byte) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_EncryptInit_ex(ctx, __type, impl, (*C.uchar)(unsafe.Pointer(key)), (*C.uchar)(unsafe.Pointer(iv)), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_EncryptInit_ex", uintptr(_err))
}

func EVP_EncryptUpdate(ctx EVP_CIPHER_CTX_PTR, out *byte, outl *int32, in *byte, inl int32) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_EncryptUpdate(ctx, (*C.uchar)(unsafe.Pointer(out)), (*C.int)(unsafe.Pointer(outl)), (*C.uchar)(unsafe.Pointer(in)), C.int(inl), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_EncryptUpdate", uintptr(_err))
}

func EVP_KDF_CTX_free(ctx EVP_KDF_CTX_PTR) {
	C._mkcgo_EVP_KDF_CTX_free(ctx)
}

func EVP_KDF_CTX_get_kdf_size(ctx EVP_KDF_CTX_PTR) (int, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_KDF_CTX_get_kdf_size(ctx, mkcgoNoEscape(&_err))
	return int(_ret), newMkcgoErr("EVP_KDF_CTX_get_kdf_size", uintptr(_err))
}

func EVP_KDF_CTX_new(kdf EVP_KDF_PTR) (EVP_KDF_CTX_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_KDF_CTX_new(kdf, mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_KDF_CTX_new", uintptr(_err))
}

func EVP_KDF_CTX_set_params(ctx EVP_KDF_CTX_PTR, params OSSL_PARAM_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_KDF_CTX_set_params(ctx, params, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_KDF_CTX_set_params", uintptr(_err))
}

func EVP_KDF_derive(ctx EVP_KDF_CTX_PTR, key *byte, keylen int, params OSSL_PARAM_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_KDF_derive(ctx, (*C.uchar)(unsafe.Pointer(key)), C.size_t(keylen), params, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_KDF_derive", uintptr(_err))
}

func EVP_KDF_fetch(libctx OSSL_LIB_CTX_PTR, algorithm *byte, properties *byte) (EVP_KDF_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_KDF_fetch(libctx, (*C.char)(unsafe.Pointer(algorithm)), (*C.char)(unsafe.Pointer(properties)), mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_KDF_fetch", uintptr(_err))
}

func EVP_KDF_free(kdf EVP_KDF_PTR) {
	C._mkcgo_EVP_KDF_free(kdf)
}

func EVP_KEYMGMT_fetch(libctx OSSL_LIB_CTX_PTR, algorithm *byte, properties *byte) (EVP_KEYMGMT_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_KEYMGMT_fetch(libctx, (*C.char)(unsafe.Pointer(algorithm)), (*C.char)(unsafe.Pointer(properties)), mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_KEYMGMT_fetch", uintptr(_err))
}

func EVP_KEYMGMT_free(keymgmt EVP_KEYMGMT_PTR) {
	C._mkcgo_EVP_KEYMGMT_free(keymgmt)
}

func EVP_MAC_CTX_dup(arg0 EVP_MAC_CTX_PTR) (EVP_MAC_CTX_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_MAC_CTX_dup(arg0, mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_MAC_CTX_dup", uintptr(_err))
}

func EVP_MAC_CTX_free(arg0 EVP_MAC_CTX_PTR) {
	C._mkcgo_EVP_MAC_CTX_free(arg0)
}

func EVP_MAC_CTX_new(arg0 EVP_MAC_PTR) (EVP_MAC_CTX_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_MAC_CTX_new(arg0, mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_MAC_CTX_new", uintptr(_err))
}

func EVP_MAC_CTX_set_params(ctx EVP_MAC_CTX_PTR, params OSSL_PARAM_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_MAC_CTX_set_params(ctx, params, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_MAC_CTX_set_params", uintptr(_err))
}

func EVP_MAC_fetch(ctx OSSL_LIB_CTX_PTR, algorithm *byte, properties *byte) (EVP_MAC_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_MAC_fetch(ctx, (*C.char)(unsafe.Pointer(algorithm)), (*C.char)(unsafe.Pointer(properties)), mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_MAC_fetch", uintptr(_err))
}

func EVP_MAC_final(ctx EVP_MAC_CTX_PTR, out *byte, outl *int, outsize int) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_MAC_final(ctx, (*C.uchar)(unsafe.Pointer(out)), (*C.size_t)(unsafe.Pointer(outl)), C.size_t(outsize), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_MAC_final", uintptr(_err))
}

func EVP_MAC_init(ctx EVP_MAC_CTX_PTR, key *byte, keylen int, params OSSL_PARAM_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_MAC_init(ctx, (*C.uchar)(unsafe.Pointer(key)), C.size_t(keylen), params, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_MAC_init", uintptr(_err))
}

func EVP_MAC_update(ctx EVP_MAC_CTX_PTR, data *byte, datalen int) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_MAC_update(ctx, (*C.uchar)(unsafe.Pointer(data)), C.size_t(datalen), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_MAC_update", uintptr(_err))
}

func EVP_MD_CTX_copy_ex(out EVP_MD_CTX_PTR, in EVP_MD_CTX_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_MD_CTX_copy_ex(out, in, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_MD_CTX_copy_ex", uintptr(_err))
}

func EVP_MD_CTX_ctrl(ctx EVP_MD_CTX_PTR, cmd int32, p1 int32, p2 unsafe.Pointer) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_MD_CTX_ctrl(ctx, C.int(cmd), C.int(p1), p2, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_MD_CTX_ctrl", uintptr(_err))
}

func EVP_MD_CTX_free(ctx EVP_MD_CTX_PTR) {
	C._mkcgo_EVP_MD_CTX_free(ctx)
}

func EVP_MD_CTX_get_params(ctx EVP_MD_CTX_PTR, params OSSL_PARAM_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_MD_CTX_get_params(ctx, params, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_MD_CTX_get_params", uintptr(_err))
}

func EVP_MD_CTX_gettable_params(ctx EVP_MD_CTX_PTR) (OSSL_PARAM_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_MD_CTX_gettable_params(ctx, mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_MD_CTX_gettable_params", uintptr(_err))
}

func EVP_MD_CTX_new() (EVP_MD_CTX_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_MD_CTX_new(mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_MD_CTX_new", uintptr(_err))
}

func EVP_MD_CTX_set_params(ctx EVP_MD_CTX_PTR, params OSSL_PARAM_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_MD_CTX_set_params(ctx, params, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_MD_CTX_set_params", uintptr(_err))
}

func EVP_MD_CTX_settable_params(ctx EVP_MD_CTX_PTR) (OSSL_PARAM_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_MD_CTX_settable_params(ctx, mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_MD_CTX_settable_params", uintptr(_err))
}

func EVP_MD_fetch(ctx OSSL_LIB_CTX_PTR, algorithm *byte, properties *byte) (EVP_MD_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_MD_fetch(ctx, (*C.char)(unsafe.Pointer(algorithm)), (*C.char)(unsafe.Pointer(properties)), mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_MD_fetch", uintptr(_err))
}

func EVP_MD_free(md EVP_MD_PTR) {
	C._mkcgo_EVP_MD_free(md)
}

func EVP_MD_get0_name(md EVP_MD_PTR) *byte {
	return (*byte)(unsafe.Pointer(C._mkcgo_EVP_MD_get0_name(md)))
}

func EVP_MD_get0_provider(md EVP_MD_PTR) OSSL_PROVIDER_PTR {
	return C._mkcgo_EVP_MD_get0_provider(md)
}

func EVP_MD_get_block_size(md EVP_MD_PTR) int32 {
	return int32(C._mkcgo_EVP_MD_get_block_size(md))
}

func EVP_MD_get_size(md EVP_MD_PTR) int32 {
	return int32(C._mkcgo_EVP_MD_get_size(md))
}

func EVP_MD_get_type(md EVP_MD_PTR) int32 {
	return int32(C._mkcgo_EVP_MD_get_type(md))
}

func EVP_PKEY_CTX_add1_hkdf_info(arg0 EVP_PKEY_CTX_PTR, arg1 *byte, arg2 int32) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_CTX_add1_hkdf_info(arg0, (*C.uchar)(unsafe.Pointer(arg1)), C.int(arg2), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_CTX_add1_hkdf_info", uintptr(_err))
}

func EVP_PKEY_CTX_ctrl(ctx EVP_PKEY_CTX_PTR, keytype int32, optype int32, cmd int32, p1 int32, p2 unsafe.Pointer) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_CTX_ctrl(ctx, C.int(keytype), C.int(optype), C.int(cmd), C.int(p1), p2, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_CTX_ctrl", uintptr(_err))
}

func EVP_PKEY_CTX_free(arg0 EVP_PKEY_CTX_PTR) {
	C._mkcgo_EVP_PKEY_CTX_free(arg0)
}

func EVP_PKEY_CTX_new(arg0 EVP_PKEY_PTR, arg1 ENGINE_PTR) (EVP_PKEY_CTX_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_CTX_new(arg0, arg1, mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_PKEY_CTX_new", uintptr(_err))
}

func EVP_PKEY_CTX_new_from_pkey(libctx OSSL_LIB_CTX_PTR, pkey EVP_PKEY_PTR, propquery *byte) (EVP_PKEY_CTX_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_CTX_new_from_pkey(libctx, pkey, (*C.char)(unsafe.Pointer(propquery)), mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_PKEY_CTX_new_from_pkey", uintptr(_err))
}

func EVP_PKEY_CTX_new_id(id int32, e ENGINE_PTR) (EVP_PKEY_CTX_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_CTX_new_id(C.int(id), e, mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_PKEY_CTX_new_id", uintptr(_err))
}

func EVP_PKEY_CTX_set0_rsa_oaep_label(ctx EVP_PKEY_CTX_PTR, label unsafe.Pointer, len int32) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_CTX_set0_rsa_oaep_label(ctx, label, C.int(len), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_CTX_set0_rsa_oaep_label", uintptr(_err))
}

func EVP_PKEY_CTX_set1_hkdf_key(arg0 EVP_PKEY_CTX_PTR, arg1 *byte, arg2 int32) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_CTX_set1_hkdf_key(arg0, (*C.uchar)(unsafe.Pointer(arg1)), C.int(arg2), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_CTX_set1_hkdf_key", uintptr(_err))
}

func EVP_PKEY_CTX_set1_hkdf_salt(arg0 EVP_PKEY_CTX_PTR, arg1 *byte, arg2 int32) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_CTX_set1_hkdf_salt(arg0, (*C.uchar)(unsafe.Pointer(arg1)), C.int(arg2), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_CTX_set1_hkdf_salt", uintptr(_err))
}

func EVP_PKEY_CTX_set_hkdf_md(arg0 EVP_PKEY_CTX_PTR, arg1 EVP_MD_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_CTX_set_hkdf_md(arg0, arg1, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_CTX_set_hkdf_md", uintptr(_err))
}

func EVP_PKEY_CTX_set_hkdf_mode(arg0 EVP_PKEY_CTX_PTR, arg1 int32) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_CTX_set_hkdf_mode(arg0, C.int(arg1), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_CTX_set_hkdf_mode", uintptr(_err))
}

func EVP_PKEY_Q_keygen_EC(ctx OSSL_LIB_CTX_PTR, propq *byte, __type *byte, arg1 *byte) (EVP_PKEY_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_Q_keygen_EC(ctx, (*C.char)(unsafe.Pointer(propq)), (*C.char)(unsafe.Pointer(__type)), (*C.char)(unsafe.Pointer(arg1)), mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_PKEY_Q_keygen_EC", uintptr(_err))
}

func EVP_PKEY_Q_keygen_ED25519(ctx OSSL_LIB_CTX_PTR, propq *byte, __type *byte) (EVP_PKEY_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_Q_keygen_ED25519(ctx, (*C.char)(unsafe.Pointer(propq)), (*C.char)(unsafe.Pointer(__type)), mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_PKEY_Q_keygen_ED25519", uintptr(_err))
}

func EVP_PKEY_Q_keygen_MLKEM(ctx OSSL_LIB_CTX_PTR, propq *byte, __type *byte) (EVP_PKEY_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_Q_keygen_MLKEM(ctx, (*C.char)(unsafe.Pointer(propq)), (*C.char)(unsafe.Pointer(__type)), mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_PKEY_Q_keygen_MLKEM", uintptr(_err))
}

func EVP_PKEY_Q_keygen_RSA(ctx OSSL_LIB_CTX_PTR, propq *byte, __type *byte, arg1 int) (EVP_PKEY_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_Q_keygen_RSA(ctx, (*C.char)(unsafe.Pointer(propq)), (*C.char)(unsafe.Pointer(__type)), C.size_t(arg1), mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_PKEY_Q_keygen_RSA", uintptr(_err))
}

func EVP_PKEY_Q_keygen_X25519(ctx OSSL_LIB_CTX_PTR, propq *byte, __type *byte) (EVP_PKEY_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_Q_keygen_X25519(ctx, (*C.char)(unsafe.Pointer(propq)), (*C.char)(unsafe.Pointer(__type)), mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_PKEY_Q_keygen_X25519", uintptr(_err))
}

func EVP_PKEY_assign(pkey EVP_PKEY_PTR, __type int32, key unsafe.Pointer) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_assign(pkey, C.int(__type), key, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_assign", uintptr(_err))
}

func EVP_PKEY_decapsulate(ctx EVP_PKEY_CTX_PTR, genkey *byte, genkeylen *int, wrappedkey *byte, wrappedkeylen int) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_decapsulate(ctx, (*C.uchar)(unsafe.Pointer(genkey)), (*C.size_t)(unsafe.Pointer(genkeylen)), (*C.uchar)(unsafe.Pointer(wrappedkey)), C.size_t(wrappedkeylen), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_decapsulate", uintptr(_err))
}

func EVP_PKEY_decapsulate_init(ctx EVP_PKEY_CTX_PTR, params OSSL_PARAM_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_decapsulate_init(ctx, params, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_decapsulate_init", uintptr(_err))
}

func EVP_PKEY_decrypt(arg0 EVP_PKEY_CTX_PTR, arg1 *byte, arg2 *int, arg3 *byte, arg4 int) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_decrypt(arg0, (*C.uchar)(unsafe.Pointer(arg1)), (*C.size_t)(unsafe.Pointer(arg2)), (*C.uchar)(unsafe.Pointer(arg3)), C.size_t(arg4), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_decrypt", uintptr(_err))
}

func EVP_PKEY_decrypt_init(arg0 EVP_PKEY_CTX_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_decrypt_init(arg0, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_decrypt_init", uintptr(_err))
}

func EVP_PKEY_derive(ctx EVP_PKEY_CTX_PTR, key *byte, keylen *int) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_derive(ctx, (*C.uchar)(unsafe.Pointer(key)), (*C.size_t)(unsafe.Pointer(keylen)), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_derive", uintptr(_err))
}

func EVP_PKEY_derive_init(ctx EVP_PKEY_CTX_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_derive_init(ctx, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_derive_init", uintptr(_err))
}

func EVP_PKEY_derive_set_peer(ctx EVP_PKEY_CTX_PTR, peer EVP_PKEY_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_derive_set_peer(ctx, peer, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_derive_set_peer", uintptr(_err))
}

func EVP_PKEY_encapsulate(ctx EVP_PKEY_CTX_PTR, wrappedkey *byte, wrappedkeylen *int, genkey *byte, genkeylen *int) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_encapsulate(ctx, (*C.uchar)(unsafe.Pointer(wrappedkey)), (*C.size_t)(unsafe.Pointer(wrappedkeylen)), (*C.uchar)(unsafe.Pointer(genkey)), (*C.size_t)(unsafe.Pointer(genkeylen)), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_encapsulate", uintptr(_err))
}

func EVP_PKEY_encapsulate_init(ctx EVP_PKEY_CTX_PTR, params OSSL_PARAM_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_encapsulate_init(ctx, params, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_encapsulate_init", uintptr(_err))
}

func EVP_PKEY_encrypt(arg0 EVP_PKEY_CTX_PTR, arg1 *byte, arg2 *int, arg3 *byte, arg4 int) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_encrypt(arg0, (*C.uchar)(unsafe.Pointer(arg1)), (*C.size_t)(unsafe.Pointer(arg2)), (*C.uchar)(unsafe.Pointer(arg3)), C.size_t(arg4), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_encrypt", uintptr(_err))
}

func EVP_PKEY_encrypt_init(arg0 EVP_PKEY_CTX_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_encrypt_init(arg0, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_encrypt_init", uintptr(_err))
}

func EVP_PKEY_free(arg0 EVP_PKEY_PTR) {
	C._mkcgo_EVP_PKEY_free(arg0)
}

func EVP_PKEY_fromdata(ctx EVP_PKEY_CTX_PTR, pkey *EVP_PKEY_PTR, selection int32, params OSSL_PARAM_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_fromdata(ctx, pkey, C.int(selection), params, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_fromdata", uintptr(_err))
}

func EVP_PKEY_fromdata_init(ctx EVP_PKEY_CTX_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_fromdata_init(ctx, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_fromdata_init", uintptr(_err))
}

func EVP_PKEY_get0_DSA(pkey EVP_PKEY_PTR) (DSA_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_get0_DSA(pkey, mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_PKEY_get0_DSA", uintptr(_err))
}

func EVP_PKEY_get0_EC_KEY(pkey EVP_PKEY_PTR) (EC_KEY_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_get0_EC_KEY(pkey, mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_PKEY_get0_EC_KEY", uintptr(_err))
}

func EVP_PKEY_get1_RSA(pkey EVP_PKEY_PTR) (RSA_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_get1_RSA(pkey, mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_PKEY_get1_RSA", uintptr(_err))
}

func EVP_PKEY_get1_encoded_public_key(pkey EVP_PKEY_PTR, ppub **byte) (int, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_get1_encoded_public_key(pkey, (**C.uchar)(unsafe.Pointer(ppub)), mkcgoNoEscape(&_err))
	return int(_ret), newMkcgoErr("EVP_PKEY_get1_encoded_public_key", uintptr(_err))
}

func EVP_PKEY_get_bits(pkey EVP_PKEY_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_get_bits(pkey, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_get_bits", uintptr(_err))
}

func EVP_PKEY_get_bn_param(pkey EVP_PKEY_PTR, key_name *byte, bn *BIGNUM_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_get_bn_param(pkey, (*C.char)(unsafe.Pointer(key_name)), bn, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_get_bn_param", uintptr(_err))
}

func EVP_PKEY_get_octet_string_param(pkey EVP_PKEY_PTR, key_name *byte, buf *byte, buf_len int, out_len *int) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_get_octet_string_param(pkey, (*C.char)(unsafe.Pointer(key_name)), (*C.uchar)(unsafe.Pointer(buf)), C.size_t(buf_len), (*C.size_t)(unsafe.Pointer(out_len)), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_get_octet_string_param", uintptr(_err))
}

func EVP_PKEY_get_raw_private_key(pkey EVP_PKEY_PTR, priv *byte, len *int) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_get_raw_private_key(pkey, (*C.uchar)(unsafe.Pointer(priv)), (*C.size_t)(unsafe.Pointer(len)), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_get_raw_private_key", uintptr(_err))
}

func EVP_PKEY_get_raw_public_key(pkey EVP_PKEY_PTR, pub *byte, len *int) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_get_raw_public_key(pkey, (*C.uchar)(unsafe.Pointer(pub)), (*C.size_t)(unsafe.Pointer(len)), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_get_raw_public_key", uintptr(_err))
}

func EVP_PKEY_get_size(pkey EVP_PKEY_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_get_size(pkey, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_get_size", uintptr(_err))
}

func EVP_PKEY_keygen(ctx EVP_PKEY_CTX_PTR, ppkey *EVP_PKEY_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_keygen(ctx, ppkey, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_keygen", uintptr(_err))
}

func EVP_PKEY_keygen_init(ctx EVP_PKEY_CTX_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_keygen_init(ctx, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_keygen_init", uintptr(_err))
}

func EVP_PKEY_new() (EVP_PKEY_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_new(mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_PKEY_new", uintptr(_err))
}

func EVP_PKEY_new_raw_private_key(__type int32, e ENGINE_PTR, key *byte, keylen int) (EVP_PKEY_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_new_raw_private_key(C.int(__type), e, (*C.uchar)(unsafe.Pointer(key)), C.size_t(keylen), mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_PKEY_new_raw_private_key", uintptr(_err))
}

func EVP_PKEY_new_raw_public_key(__type int32, e ENGINE_PTR, key *byte, keylen int) (EVP_PKEY_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_new_raw_public_key(C.int(__type), e, (*C.uchar)(unsafe.Pointer(key)), C.size_t(keylen), mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_PKEY_new_raw_public_key", uintptr(_err))
}

func EVP_PKEY_paramgen(ctx EVP_PKEY_CTX_PTR, ppkey *EVP_PKEY_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_paramgen(ctx, ppkey, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_paramgen", uintptr(_err))
}

func EVP_PKEY_paramgen_init(ctx EVP_PKEY_CTX_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_paramgen_init(ctx, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_paramgen_init", uintptr(_err))
}

func EVP_PKEY_private_check(ctx EVP_PKEY_CTX_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_private_check(ctx, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_private_check", uintptr(_err))
}

func EVP_PKEY_public_check_quick(ctx EVP_PKEY_CTX_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_public_check_quick(ctx, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_public_check_quick", uintptr(_err))
}

func EVP_PKEY_set1_EC_KEY(pkey EVP_PKEY_PTR, key EC_KEY_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_set1_EC_KEY(pkey, key, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_set1_EC_KEY", uintptr(_err))
}

func EVP_PKEY_set1_encoded_public_key(pkey EVP_PKEY_PTR, pub *byte, publen int) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_set1_encoded_public_key(pkey, (*C.uchar)(unsafe.Pointer(pub)), C.size_t(publen), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_set1_encoded_public_key", uintptr(_err))
}

func EVP_PKEY_sign(arg0 EVP_PKEY_CTX_PTR, arg1 *byte, arg2 *int, arg3 *byte, arg4 int) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_sign(arg0, (*C.uchar)(unsafe.Pointer(arg1)), (*C.size_t)(unsafe.Pointer(arg2)), (*C.uchar)(unsafe.Pointer(arg3)), C.size_t(arg4), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_sign", uintptr(_err))
}

func EVP_PKEY_sign_init(arg0 EVP_PKEY_CTX_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_sign_init(arg0, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_sign_init", uintptr(_err))
}

func EVP_PKEY_up_ref(key EVP_PKEY_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_up_ref(key, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_up_ref", uintptr(_err))
}

func EVP_PKEY_verify(ctx EVP_PKEY_CTX_PTR, sig *byte, siglen int, tbs *byte, tbslen int) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_verify(ctx, (*C.uchar)(unsafe.Pointer(sig)), C.size_t(siglen), (*C.uchar)(unsafe.Pointer(tbs)), C.size_t(tbslen), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_verify", uintptr(_err))
}

func EVP_PKEY_verify_init(arg0 EVP_PKEY_CTX_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_PKEY_verify_init(arg0, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_PKEY_verify_init", uintptr(_err))
}

func EVP_SIGNATURE_fetch(ctx OSSL_LIB_CTX_PTR, algorithm *byte, properties *byte) (EVP_SIGNATURE_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_SIGNATURE_fetch(ctx, (*C.char)(unsafe.Pointer(algorithm)), (*C.char)(unsafe.Pointer(properties)), mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("EVP_SIGNATURE_fetch", uintptr(_err))
}

func EVP_SIGNATURE_free(signature EVP_SIGNATURE_PTR) {
	C._mkcgo_EVP_SIGNATURE_free(signature)
}

func EVP_aes_128_cbc() EVP_CIPHER_PTR {
	return C._mkcgo_EVP_aes_128_cbc()
}

func EVP_aes_128_ctr() EVP_CIPHER_PTR {
	return C._mkcgo_EVP_aes_128_ctr()
}

func EVP_aes_128_ecb() EVP_CIPHER_PTR {
	return C._mkcgo_EVP_aes_128_ecb()
}

func EVP_aes_128_gcm() EVP_CIPHER_PTR {
	return C._mkcgo_EVP_aes_128_gcm()
}

func EVP_aes_192_cbc() EVP_CIPHER_PTR {
	return C._mkcgo_EVP_aes_192_cbc()
}

func EVP_aes_192_ctr() EVP_CIPHER_PTR {
	return C._mkcgo_EVP_aes_192_ctr()
}

func EVP_aes_192_ecb() EVP_CIPHER_PTR {
	return C._mkcgo_EVP_aes_192_ecb()
}

func EVP_aes_192_gcm() EVP_CIPHER_PTR {
	return C._mkcgo_EVP_aes_192_gcm()
}

func EVP_aes_256_cbc() EVP_CIPHER_PTR {
	return C._mkcgo_EVP_aes_256_cbc()
}

func EVP_aes_256_ctr() EVP_CIPHER_PTR {
	return C._mkcgo_EVP_aes_256_ctr()
}

func EVP_aes_256_ecb() EVP_CIPHER_PTR {
	return C._mkcgo_EVP_aes_256_ecb()
}

func EVP_aes_256_gcm() EVP_CIPHER_PTR {
	return C._mkcgo_EVP_aes_256_gcm()
}

func EVP_default_properties_enable_fips(libctx OSSL_LIB_CTX_PTR, enable int32) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_EVP_default_properties_enable_fips(libctx, C.int(enable), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("EVP_default_properties_enable_fips", uintptr(_err))
}

func EVP_default_properties_is_fips_enabled(libctx OSSL_LIB_CTX_PTR) int32 {
	return int32(C._mkcgo_EVP_default_properties_is_fips_enabled(libctx))
}

func EVP_des_cbc() EVP_CIPHER_PTR {
	return C._mkcgo_EVP_des_cbc()
}

func EVP_des_ecb() EVP_CIPHER_PTR {
	return C._mkcgo_EVP_des_ecb()
}

func EVP_des_ede3_cbc() EVP_CIPHER_PTR {
	return C._mkcgo_EVP_des_ede3_cbc()
}

func EVP_des_ede3_ecb() EVP_CIPHER_PTR {
	return C._mkcgo_EVP_des_ede3_ecb()
}

func EVP_md4() EVP_MD_PTR {
	return C._mkcgo_EVP_md4()
}

func EVP_md5() EVP_MD_PTR {
	return C._mkcgo_EVP_md5()
}

func EVP_md5_sha1() EVP_MD_PTR {
	return C._mkcgo_EVP_md5_sha1()
}

func EVP_rc4() EVP_CIPHER_PTR {
	return C._mkcgo_EVP_rc4()
}

func EVP_ripemd160() EVP_MD_PTR {
	return C._mkcgo_EVP_ripemd160()
}

func EVP_sha1() EVP_MD_PTR {
	return C._mkcgo_EVP_sha1()
}

func EVP_sha224() EVP_MD_PTR {
	return C._mkcgo_EVP_sha224()
}

func EVP_sha256() EVP_MD_PTR {
	return C._mkcgo_EVP_sha256()
}

func EVP_sha384() EVP_MD_PTR {
	return C._mkcgo_EVP_sha384()
}

func EVP_sha3_224() EVP_MD_PTR {
	return C._mkcgo_EVP_sha3_224()
}

func EVP_sha3_256() EVP_MD_PTR {
	return C._mkcgo_EVP_sha3_256()
}

func EVP_sha3_384() EVP_MD_PTR {
	return C._mkcgo_EVP_sha3_384()
}

func EVP_sha3_512() EVP_MD_PTR {
	return C._mkcgo_EVP_sha3_512()
}

func EVP_sha512() EVP_MD_PTR {
	return C._mkcgo_EVP_sha512()
}

func EVP_sha512_224() EVP_MD_PTR {
	return C._mkcgo_EVP_sha512_224()
}

func EVP_sha512_256() EVP_MD_PTR {
	return C._mkcgo_EVP_sha512_256()
}

func FIPS_mode() int32 {
	return int32(C._mkcgo_FIPS_mode())
}

func FIPS_mode_set(r int32) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_FIPS_mode_set(C.int(r), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("FIPS_mode_set", uintptr(_err))
}

func HMAC_CTX_copy(dest HMAC_CTX_PTR, src HMAC_CTX_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_HMAC_CTX_copy(dest, src, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("HMAC_CTX_copy", uintptr(_err))
}

func HMAC_CTX_free(arg0 HMAC_CTX_PTR) {
	C._mkcgo_HMAC_CTX_free(arg0)
}

func HMAC_CTX_new() (HMAC_CTX_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_HMAC_CTX_new(mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("HMAC_CTX_new", uintptr(_err))
}

func HMAC_Final(arg0 HMAC_CTX_PTR, arg1 *byte, arg2 *uint32) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_HMAC_Final(arg0, (*C.uchar)(unsafe.Pointer(arg1)), (*C.uint)(unsafe.Pointer(arg2)), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("HMAC_Final", uintptr(_err))
}

func HMAC_Init_ex(arg0 HMAC_CTX_PTR, arg1 unsafe.Pointer, arg2 int32, arg3 EVP_MD_PTR, arg4 ENGINE_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_HMAC_Init_ex(arg0, arg1, C.int(arg2), arg3, arg4, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("HMAC_Init_ex", uintptr(_err))
}

func HMAC_Update(arg0 HMAC_CTX_PTR, arg1 *byte, arg2 int) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_HMAC_Update(arg0, (*C.uchar)(unsafe.Pointer(arg1)), C.size_t(arg2), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("HMAC_Update", uintptr(_err))
}

func OBJ_nid2sn(n int32) *byte {
	return (*byte)(unsafe.Pointer(C._mkcgo_OBJ_nid2sn(C.int(n))))
}

func OPENSSL_init() {
	C._mkcgo_OPENSSL_init()
}

func OPENSSL_init_crypto(ops uint64, settings OPENSSL_INIT_SETTINGS_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_OPENSSL_init_crypto(C.uint64_t(ops), settings, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("OPENSSL_init_crypto", uintptr(_err))
}

func OPENSSL_version_major_Available() bool {
	return C._mkcgo_available_OPENSSL_version_major() != 0
}

func OPENSSL_version_major() uint32 {
	return uint32(C._mkcgo_OPENSSL_version_major())
}

func OPENSSL_version_minor_Available() bool {
	return C._mkcgo_available_OPENSSL_version_minor() != 0
}

func OPENSSL_version_minor() uint32 {
	return uint32(C._mkcgo_OPENSSL_version_minor())
}

func OPENSSL_version_patch_Available() bool {
	return C._mkcgo_available_OPENSSL_version_patch() != 0
}

func OPENSSL_version_patch() uint32 {
	return uint32(C._mkcgo_OPENSSL_version_patch())
}

func OSSL_PARAM_BLD_free(bld OSSL_PARAM_BLD_PTR) {
	C._mkcgo_OSSL_PARAM_BLD_free(bld)
}

func OSSL_PARAM_BLD_new() (OSSL_PARAM_BLD_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_OSSL_PARAM_BLD_new(mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("OSSL_PARAM_BLD_new", uintptr(_err))
}

func OSSL_PARAM_BLD_push_BN(bld OSSL_PARAM_BLD_PTR, key *byte, bn BIGNUM_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_OSSL_PARAM_BLD_push_BN(bld, (*C.char)(unsafe.Pointer(key)), bn, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("OSSL_PARAM_BLD_push_BN", uintptr(_err))
}

func OSSL_PARAM_BLD_push_int32(bld OSSL_PARAM_BLD_PTR, key *byte, num int32) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_OSSL_PARAM_BLD_push_int32(bld, (*C.char)(unsafe.Pointer(key)), C.int32_t(num), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("OSSL_PARAM_BLD_push_int32", uintptr(_err))
}

func OSSL_PARAM_BLD_push_octet_string(bld OSSL_PARAM_BLD_PTR, key *byte, buf unsafe.Pointer, bsize int) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_OSSL_PARAM_BLD_push_octet_string(bld, (*C.char)(unsafe.Pointer(key)), buf, C.size_t(bsize), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("OSSL_PARAM_BLD_push_octet_string", uintptr(_err))
}

func OSSL_PARAM_BLD_push_utf8_string(bld OSSL_PARAM_BLD_PTR, key *byte, buf *byte, bsize int) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_OSSL_PARAM_BLD_push_utf8_string(bld, (*C.char)(unsafe.Pointer(key)), (*C.char)(unsafe.Pointer(buf)), C.size_t(bsize), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("OSSL_PARAM_BLD_push_utf8_string", uintptr(_err))
}

func OSSL_PARAM_BLD_to_param(bld OSSL_PARAM_BLD_PTR) (OSSL_PARAM_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_OSSL_PARAM_BLD_to_param(bld, mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("OSSL_PARAM_BLD_to_param", uintptr(_err))
}

func OSSL_PARAM_free(p OSSL_PARAM_PTR) {
	C._mkcgo_OSSL_PARAM_free(p)
}

func OSSL_PARAM_locate_const(p OSSL_PARAM_PTR, key *byte) (OSSL_PARAM_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_OSSL_PARAM_locate_const(p, (*C.char)(unsafe.Pointer(key)), mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("OSSL_PARAM_locate_const", uintptr(_err))
}

func OSSL_PROVIDER_available(libctx OSSL_LIB_CTX_PTR, name *byte) int32 {
	return int32(C._mkcgo_OSSL_PROVIDER_available(libctx, (*C.char)(unsafe.Pointer(name))))
}

func OSSL_PROVIDER_get0_name(prov OSSL_PROVIDER_PTR) *byte {
	return (*byte)(unsafe.Pointer(C._mkcgo_OSSL_PROVIDER_get0_name(prov)))
}

func OSSL_PROVIDER_try_load(libctx OSSL_LIB_CTX_PTR, name *byte, retain_fallbacks int32) (OSSL_PROVIDER_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_OSSL_PROVIDER_try_load(libctx, (*C.char)(unsafe.Pointer(name)), C.int(retain_fallbacks), mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("OSSL_PROVIDER_try_load", uintptr(_err))
}

func OpenSSL_version(__type int32) *byte {
	return (*byte)(unsafe.Pointer(C._mkcgo_OpenSSL_version(C.int(__type))))
}

func OpenSSL_version_num_Available() bool {
	return C._mkcgo_available_OpenSSL_version_num() != 0
}

func OpenSSL_version_num() uint64 {
	return uint64(C._mkcgo_OpenSSL_version_num())
}

func PKCS5_PBKDF2_HMAC(pass *byte, passlen int32, salt *byte, saltlen int32, iter int32, digest EVP_MD_PTR, keylen int32, out *byte) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_PKCS5_PBKDF2_HMAC((*C.char)(unsafe.Pointer(pass)), C.int(passlen), (*C.uchar)(unsafe.Pointer(salt)), C.int(saltlen), C.int(iter), digest, C.int(keylen), (*C.uchar)(unsafe.Pointer(out)), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("PKCS5_PBKDF2_HMAC", uintptr(_err))
}

func RAND_bytes(arg0 *byte, arg1 int32) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_RAND_bytes((*C.uchar)(unsafe.Pointer(arg0)), C.int(arg1), mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("RAND_bytes", uintptr(_err))
}

func RSA_free(arg0 RSA_PTR) {
	C._mkcgo_RSA_free(arg0)
}

func RSA_get0_crt_params(r RSA_PTR, dmp1 *BIGNUM_PTR, dmq1 *BIGNUM_PTR, iqmp *BIGNUM_PTR) {
	C._mkcgo_RSA_get0_crt_params(r, dmp1, dmq1, iqmp)
}

func RSA_get0_factors(rsa RSA_PTR, p *BIGNUM_PTR, q *BIGNUM_PTR) {
	C._mkcgo_RSA_get0_factors(rsa, p, q)
}

func RSA_get0_key(rsa RSA_PTR, n *BIGNUM_PTR, e *BIGNUM_PTR, d *BIGNUM_PTR) {
	C._mkcgo_RSA_get0_key(rsa, n, e, d)
}

func RSA_new() (RSA_PTR, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_RSA_new(mkcgoNoEscape(&_err))
	return _ret, newMkcgoErr("RSA_new", uintptr(_err))
}

func RSA_set0_crt_params(rsa RSA_PTR, dmp1 BIGNUM_PTR, dmp2 BIGNUM_PTR, iqmp BIGNUM_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_RSA_set0_crt_params(rsa, dmp1, dmp2, iqmp, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("RSA_set0_crt_params", uintptr(_err))
}

func RSA_set0_factors(rsa RSA_PTR, p BIGNUM_PTR, q BIGNUM_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_RSA_set0_factors(rsa, p, q, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("RSA_set0_factors", uintptr(_err))
}

func RSA_set0_key(r RSA_PTR, n BIGNUM_PTR, e BIGNUM_PTR, d BIGNUM_PTR) (int32, error) {
	var _err C.uintptr_t
	_ret := C._mkcgo_RSA_set0_key(r, n, e, d, mkcgoNoEscape(&_err))
	return int32(_ret), newMkcgoErr("RSA_set0_key", uintptr(_err))
}
