// Code generated by mkcgo. DO NOT EDIT.

//go:build go1.24 && !cmd_go_bootstrap

package ossl

/*
#cgo noescape _mkcgo_BIO_ctrl
#cgo nocallback _mkcgo_BIO_ctrl
#cgo noescape _mkcgo_BIO_free
#cgo nocallback _mkcgo_BIO_free
#cgo noescape _mkcgo_ERR_print_errors
#cgo nocallback _mkcgo_ERR_print_errors
#cgo noescape _mkcgo_EVP_CipherUpdate
#cgo nocallback _mkcgo_EVP_CipherUpdate
#cgo noescape _mkcgo_EVP_DecryptFinal_ex
#cgo nocallback _mkcgo_EVP_DecryptFinal_ex
#cgo noescape _mkcgo_EVP_DecryptUpdate
#cgo nocallback _mkcgo_EVP_DecryptUpdate
#cgo noescape _mkcgo_EVP_Digest
#cgo nocallback _mkcgo_EVP_Digest
#cgo noescape _mkcgo_EVP_DigestFinalXOF
#cgo nocallback _mkcgo_EVP_DigestFinalXOF
#cgo noescape _mkcgo_EVP_DigestFinal_ex
#cgo nocallback _mkcgo_EVP_DigestFinal_ex
#cgo noescape _mkcgo_EVP_DigestSign
#cgo nocallback _mkcgo_EVP_DigestSign
#cgo noescape _mkcgo_EVP_DigestSqueeze
#cgo nocallback _mkcgo_EVP_DigestSqueeze
#cgo noescape _mkcgo_EVP_DigestUpdate
#cgo nocallback _mkcgo_EVP_DigestUpdate
#cgo noescape _mkcgo_EVP_EncryptFinal_ex
#cgo nocallback _mkcgo_EVP_EncryptFinal_ex
#cgo noescape _mkcgo_EVP_EncryptUpdate
#cgo nocallback _mkcgo_EVP_EncryptUpdate
#cgo noescape _mkcgo_EVP_MAC_CTX_free
#cgo nocallback _mkcgo_EVP_MAC_CTX_free
#cgo noescape _mkcgo_EVP_MAC_final
#cgo nocallback _mkcgo_EVP_MAC_final
#cgo noescape _mkcgo_EVP_MAC_init
#cgo nocallback _mkcgo_EVP_MAC_init
#cgo noescape _mkcgo_EVP_MAC_update
#cgo nocallback _mkcgo_EVP_MAC_update
#cgo noescape _mkcgo_EVP_MD_CTX_get_params
#cgo nocallback _mkcgo_EVP_MD_CTX_get_params
#cgo noescape _mkcgo_EVP_MD_CTX_set_params
#cgo nocallback _mkcgo_EVP_MD_CTX_set_params
#cgo noescape _mkcgo_EVP_PKEY_Q_keygen_EC
#cgo nocallback _mkcgo_EVP_PKEY_Q_keygen_EC
#cgo noescape _mkcgo_EVP_PKEY_Q_keygen_ED25519
#cgo nocallback _mkcgo_EVP_PKEY_Q_keygen_ED25519
#cgo noescape _mkcgo_EVP_PKEY_Q_keygen_MLKEM
#cgo nocallback _mkcgo_EVP_PKEY_Q_keygen_MLKEM
#cgo noescape _mkcgo_EVP_PKEY_Q_keygen_RSA
#cgo nocallback _mkcgo_EVP_PKEY_Q_keygen_RSA
#cgo noescape _mkcgo_EVP_PKEY_Q_keygen_X25519
#cgo nocallback _mkcgo_EVP_PKEY_Q_keygen_X25519
#cgo noescape _mkcgo_EVP_PKEY_derive
#cgo nocallback _mkcgo_EVP_PKEY_derive
#cgo noescape _mkcgo_EVP_PKEY_get_bn_param
#cgo nocallback _mkcgo_EVP_PKEY_get_bn_param
#cgo noescape _mkcgo_EVP_PKEY_get_raw_private_key
#cgo nocallback _mkcgo_EVP_PKEY_get_raw_private_key
#cgo noescape _mkcgo_EVP_PKEY_get_raw_public_key
#cgo nocallback _mkcgo_EVP_PKEY_get_raw_public_key
#cgo noescape _mkcgo_EVP_PKEY_keygen
#cgo nocallback _mkcgo_EVP_PKEY_keygen
#cgo noescape _mkcgo_HMAC_CTX_copy
#cgo nocallback _mkcgo_HMAC_CTX_copy
#cgo noescape _mkcgo_HMAC_CTX_free
#cgo nocallback _mkcgo_HMAC_CTX_free
#cgo noescape _mkcgo_HMAC_Final
#cgo nocallback _mkcgo_HMAC_Final
#cgo noescape _mkcgo_HMAC_Init_ex
#cgo nocallback _mkcgo_HMAC_Init_ex
#cgo noescape _mkcgo_HMAC_Update
#cgo nocallback _mkcgo_HMAC_Update
#cgo noescape _mkcgo_RAND_bytes
#cgo nocallback _mkcgo_RAND_bytes
*/
import "C"
