// Code generated by mkcgo. DO NOT EDIT.

package ossl

const (
	POINT_CONVERSION_UNCOMPRESSED       = 4
	OPENSSL_INIT_LOAD_CRYPTO_STRINGS    = 0x00000002
	OPENSSL_INIT_ADD_ALL_CIPHERS        = 0x00000004
	OPENSSL_INIT_ADD_ALL_DIGESTS        = 0x00000008
	OPENSSL_INIT_LOAD_CONFIG            = 0x00000040
	EVP_CTRL_GCM_GET_TAG                = 0x10
	EVP_CTRL_GCM_SET_TAG                = 0x11
	EVP_PKEY_CTRL_MD                    = 1
	EVP_PKEY_RSA                        = 6
	EVP_PKEY_EC                         = 408
	EVP_PKEY_TLS1_PRF                   = 1021
	EVP_PKEY_X25519                     = 1034
	EVP_PKEY_HKDF                       = 1036
	EVP_PKEY_ED25519                    = 1087
	EVP_PKEY_DSA                        = 116
	EVP_PKEY_MLKEM_768                  = 1455
	EVP_PKEY_MLKEM_1024                 = 1456
	EVP_PKEY_OP_DERIVE                  = (1 << 10)
	EVP_MAX_MD_SIZE                     = 64
	EVP_PKEY_PUBLIC_KEY                 = 0x86
	EVP_PKEY_KEYPAIR                    = 0x87
	EVP_PKEY_CTRL_EC_PARAMGEN_CURVE_NID = 0x1001
	EVP_KDF_HKDF_MODE_EXTRACT_ONLY      = 1
	EVP_KDF_HKDF_MODE_EXPAND_ONLY       = 2
	EVP_PKEY_CTRL_TLS_MD                = 0x1000
	EVP_PKEY_CTRL_TLS_SECRET            = 0x1001
	EVP_PKEY_CTRL_TLS_SEED              = 0x1002
	EVP_PKEY_CTRL_HKDF_MD               = 0x1003
	EVP_PKEY_CTRL_HKDF_SALT             = 0x1004
	EVP_PKEY_CTRL_HKDF_KEY              = 0x1005
	EVP_PKEY_CTRL_HKDF_INFO             = 0x1006
	EVP_PKEY_CTRL_HKDF_MODE             = 0x1007
	NID_X9_62_prime256v1                = 415
	NID_secp224r1                       = 713
	NID_secp384r1                       = 715
	NID_secp521r1                       = 716
	NID_ML_KEM_768                      = 1455
	NID_ML_KEM_1024                     = 1456
	RSA_PKCS1_PADDING                   = 1
	RSA_NO_PADDING                      = 3
	RSA_PKCS1_OAEP_PADDING              = 4
	RSA_PKCS1_PSS_PADDING               = 6
	RSA_PSS_SALTLEN_DIGEST              = -1
	RSA_PSS_SALTLEN_AUTO                = -2
	RSA_PSS_SALTLEN_MAX_SIGN            = -2
	RSA_PSS_SALTLEN_MAX                 = -3
	EVP_PKEY_CTRL_RSA_PADDING           = 0x1001
	EVP_PKEY_CTRL_RSA_PSS_SALTLEN       = 0x1002
	EVP_PKEY_CTRL_RSA_KEYGEN_BITS       = 0x1003
	EVP_PKEY_CTRL_RSA_MGF1_MD           = 0x1005
	EVP_PKEY_CTRL_RSA_OAEP_MD           = 0x1009
	EVP_PKEY_CTRL_RSA_OAEP_LABEL        = 0x100A
	EVP_PKEY_CTRL_DSA_PARAMGEN_BITS     = 0x1001
	EVP_PKEY_CTRL_DSA_PARAMGEN_Q_BITS   = 0x1002
	OSSL_PARAM_INTEGER                  = 1
	OSSL_PARAM_OCTET_STRING             = 5
	BIO_CTRL_INFO                       = 3
)
