// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Code generated by mkcgo. DO NOT EDIT.

//go:build goexperiment.cgo2 && cgo && (linux || darwin) && (amd64 || arm64)

package ossl

/*
#cgo noescape fp__mkcgo_func_BIO_ctrl
#cgo nocallback fp__mkcgo_func_BIO_ctrl
#cgo noescape fp__mkcgo_func_BIO_free
#cgo nocallback fp__mkcgo_func_BIO_free
#cgo noescape fp__mkcgo_func_ERR_print_errors
#cgo nocallback fp__mkcgo_func_ERR_print_errors
#cgo noescape fp__mkcgo_func_EVP_CipherUpdate
#cgo nocallback fp__mkcgo_func_EVP_CipherUpdate
#cgo noescape fp__mkcgo_func_EVP_DecryptFinal_ex
#cgo nocallback fp__mkcgo_func_EVP_DecryptFinal_ex
#cgo noescape fp__mkcgo_func_EVP_DecryptUpdate
#cgo nocallback fp__mkcgo_func_EVP_DecryptUpdate
#cgo noescape fp__mkcgo_func_EVP_Digest
#cgo nocallback fp__mkcgo_func_EVP_Digest
#cgo noescape fp__mkcgo_func_EVP_DigestFinalXOF
#cgo nocallback fp__mkcgo_func_EVP_DigestFinalXOF
#cgo noescape fp__mkcgo_func_EVP_DigestFinal_ex
#cgo nocallback fp__mkcgo_func_EVP_DigestFinal_ex
#cgo noescape fp__mkcgo_func_EVP_DigestSign
#cgo nocallback fp__mkcgo_func_EVP_DigestSign
#cgo noescape fp__mkcgo_func_EVP_DigestSqueeze
#cgo nocallback fp__mkcgo_func_EVP_DigestSqueeze
#cgo noescape fp__mkcgo_func_EVP_DigestUpdate
#cgo nocallback fp__mkcgo_func_EVP_DigestUpdate
#cgo noescape fp__mkcgo_func_EVP_EncryptFinal_ex
#cgo nocallback fp__mkcgo_func_EVP_EncryptFinal_ex
#cgo noescape fp__mkcgo_func_EVP_EncryptUpdate
#cgo nocallback fp__mkcgo_func_EVP_EncryptUpdate
#cgo noescape fp__mkcgo_func_EVP_MAC_CTX_free
#cgo nocallback fp__mkcgo_func_EVP_MAC_CTX_free
#cgo noescape fp__mkcgo_func_EVP_MAC_final
#cgo nocallback fp__mkcgo_func_EVP_MAC_final
#cgo noescape fp__mkcgo_func_EVP_MAC_init
#cgo nocallback fp__mkcgo_func_EVP_MAC_init
#cgo noescape fp__mkcgo_func_EVP_MAC_update
#cgo nocallback fp__mkcgo_func_EVP_MAC_update
#cgo noescape fp__mkcgo_func_EVP_MD_CTX_get_params
#cgo nocallback fp__mkcgo_func_EVP_MD_CTX_get_params
#cgo noescape fp__mkcgo_func_EVP_MD_CTX_set_params
#cgo nocallback fp__mkcgo_func_EVP_MD_CTX_set_params
#cgo noescape fp__mkcgo_func_EVP_PKEY_CTX_set_params
#cgo nocallback fp__mkcgo_func_EVP_PKEY_CTX_set_params
#cgo noescape fp__mkcgo_func_EVP_PKEY_Q_keygen_EC
#cgo nocallback fp__mkcgo_func_EVP_PKEY_Q_keygen_EC
#cgo noescape fp__mkcgo_func_EVP_PKEY_Q_keygen_ED25519
#cgo nocallback fp__mkcgo_func_EVP_PKEY_Q_keygen_ED25519
#cgo noescape fp__mkcgo_func_EVP_PKEY_Q_keygen_MLDSA
#cgo nocallback fp__mkcgo_func_EVP_PKEY_Q_keygen_MLDSA
#cgo noescape fp__mkcgo_func_EVP_PKEY_Q_keygen_MLKEM
#cgo nocallback fp__mkcgo_func_EVP_PKEY_Q_keygen_MLKEM
#cgo noescape fp__mkcgo_func_EVP_PKEY_Q_keygen_RSA
#cgo nocallback fp__mkcgo_func_EVP_PKEY_Q_keygen_RSA
#cgo noescape fp__mkcgo_func_EVP_PKEY_Q_keygen_X25519
#cgo nocallback fp__mkcgo_func_EVP_PKEY_Q_keygen_X25519
#cgo noescape fp__mkcgo_func_EVP_PKEY_derive
#cgo nocallback fp__mkcgo_func_EVP_PKEY_derive
#cgo noescape fp__mkcgo_func_EVP_PKEY_eq
#cgo nocallback fp__mkcgo_func_EVP_PKEY_eq
#cgo noescape fp__mkcgo_func_EVP_PKEY_get_bn_param
#cgo nocallback fp__mkcgo_func_EVP_PKEY_get_bn_param
#cgo noescape fp__mkcgo_func_EVP_PKEY_get_raw_private_key
#cgo nocallback fp__mkcgo_func_EVP_PKEY_get_raw_private_key
#cgo noescape fp__mkcgo_func_EVP_PKEY_get_raw_public_key
#cgo nocallback fp__mkcgo_func_EVP_PKEY_get_raw_public_key
#cgo noescape fp__mkcgo_func_EVP_PKEY_keygen
#cgo nocallback fp__mkcgo_func_EVP_PKEY_keygen
#cgo noescape fp__mkcgo_func_HMAC_CTX_copy
#cgo nocallback fp__mkcgo_func_HMAC_CTX_copy
#cgo noescape fp__mkcgo_func_HMAC_CTX_free
#cgo nocallback fp__mkcgo_func_HMAC_CTX_free
#cgo noescape fp__mkcgo_func_HMAC_Final
#cgo nocallback fp__mkcgo_func_HMAC_Final
#cgo noescape fp__mkcgo_func_HMAC_Init_ex
#cgo nocallback fp__mkcgo_func_HMAC_Init_ex
#cgo noescape fp__mkcgo_func_HMAC_Update
#cgo nocallback fp__mkcgo_func_HMAC_Update
#cgo noescape fp__mkcgo_func_RAND_bytes
#cgo nocallback fp__mkcgo_func_RAND_bytes
#cgo noescape fp__mkcgo_func_RAND_bytes_ex
#cgo nocallback fp__mkcgo_func_RAND_bytes_ex
#cgo noescape mkcgo_dlsym_zossl
#cgo nocallback mkcgo_dlsym_zossl
*/
import "C"
import "unsafe"

//cgo:binding C._OPENSSL_INIT_SETTINGS_PTR
type OPENSSL_INIT_SETTINGS_PTR unsafe.Pointer

//cgo:binding C._OSSL_LIB_CTX_PTR
type OSSL_LIB_CTX_PTR unsafe.Pointer

//cgo:binding C._OSSL_PROVIDER_PTR
type OSSL_PROVIDER_PTR unsafe.Pointer

//cgo:binding C._ENGINE_PTR
type ENGINE_PTR unsafe.Pointer

//cgo:binding C._EVP_PKEY_PTR
type EVP_PKEY_PTR unsafe.Pointer

//cgo:binding C._EVP_PKEY_CTX_PTR
type EVP_PKEY_CTX_PTR unsafe.Pointer

//cgo:binding C._EVP_MD_PTR
type EVP_MD_PTR unsafe.Pointer

//cgo:binding C._EVP_MD_CTX_PTR
type EVP_MD_CTX_PTR unsafe.Pointer

//cgo:binding C._HMAC_CTX_PTR
type HMAC_CTX_PTR unsafe.Pointer

//cgo:binding C._EVP_CIPHER_PTR
type EVP_CIPHER_PTR unsafe.Pointer

//cgo:binding C._EVP_CIPHER_CTX_PTR
type EVP_CIPHER_CTX_PTR unsafe.Pointer

//cgo:binding C._EC_KEY_PTR
type EC_KEY_PTR unsafe.Pointer

//cgo:binding C._EC_POINT_PTR
type EC_POINT_PTR unsafe.Pointer

//cgo:binding C._EC_GROUP_PTR
type EC_GROUP_PTR unsafe.Pointer

//cgo:binding C._RSA_PTR
type RSA_PTR unsafe.Pointer

//cgo:binding C._BIGNUM_PTR
type BIGNUM_PTR unsafe.Pointer

//cgo:binding C._BN_CTX_PTR
type BN_CTX_PTR unsafe.Pointer

//cgo:binding C._EVP_MAC_PTR
type EVP_MAC_PTR unsafe.Pointer

//cgo:binding C._EVP_MAC_CTX_PTR
type EVP_MAC_CTX_PTR unsafe.Pointer

//cgo:binding C._OSSL_PARAM_BLD_PTR
type OSSL_PARAM_BLD_PTR unsafe.Pointer

//cgo:binding C._OSSL_PARAM_PTR
type OSSL_PARAM_PTR unsafe.Pointer

//cgo:binding C._EVP_SIGNATURE_PTR
type EVP_SIGNATURE_PTR unsafe.Pointer

//cgo:binding C._EVP_KEYMGMT_PTR
type EVP_KEYMGMT_PTR unsafe.Pointer

//cgo:binding C._DSA_PTR
type DSA_PTR unsafe.Pointer

//cgo:binding C._EVP_KDF_PTR
type EVP_KDF_PTR unsafe.Pointer

//cgo:binding C._EVP_KDF_CTX_PTR
type EVP_KDF_CTX_PTR unsafe.Pointer

//cgo:binding C._BIO_METHOD_PTR
type BIO_METHOD_PTR unsafe.Pointer

//cgo:binding C._BIO_PTR
type BIO_PTR unsafe.Pointer

//cgo:binding C.point_conversion_form_t
type Point_conversion_form_t = int32

//cgo:binding C._POINT_CONVERSION_UNCOMPRESSED
const POINT_CONVERSION_UNCOMPRESSED = 4

//cgo:binding C._OPENSSL_INIT_LOAD_CRYPTO_STRINGS
const OPENSSL_INIT_LOAD_CRYPTO_STRINGS = 0x00000002

//cgo:binding C._OPENSSL_INIT_ADD_ALL_CIPHERS
const OPENSSL_INIT_ADD_ALL_CIPHERS = 0x00000004

//cgo:binding C._OPENSSL_INIT_ADD_ALL_DIGESTS
const OPENSSL_INIT_ADD_ALL_DIGESTS = 0x00000008

//cgo:binding C._OPENSSL_INIT_LOAD_CONFIG
const OPENSSL_INIT_LOAD_CONFIG = 0x00000040

//cgo:binding C._EVP_CTRL_GCM_GET_TAG
const EVP_CTRL_GCM_GET_TAG = 0x10

//cgo:binding C._EVP_CTRL_GCM_SET_TAG
const EVP_CTRL_GCM_SET_TAG = 0x11

//cgo:binding C._EVP_CTRL_AEAD_SET_IVLEN
const EVP_CTRL_AEAD_SET_IVLEN = 0x9

//cgo:binding C._EVP_CTRL_AEAD_GET_TAG
const EVP_CTRL_AEAD_GET_TAG = 0x10

//cgo:binding C._EVP_CTRL_AEAD_SET_TAG
const EVP_CTRL_AEAD_SET_TAG = 0x11

//cgo:binding C._EVP_PKEY_CTRL_MD
const EVP_PKEY_CTRL_MD = 1

//cgo:binding C._EVP_PKEY_RSA
const EVP_PKEY_RSA = 6

//cgo:binding C._EVP_PKEY_EC
const EVP_PKEY_EC = 408

//cgo:binding C._EVP_PKEY_TLS1_PRF
const EVP_PKEY_TLS1_PRF = 1021

//cgo:binding C._EVP_PKEY_X25519
const EVP_PKEY_X25519 = 1034

//cgo:binding C._EVP_PKEY_HKDF
const EVP_PKEY_HKDF = 1036

//cgo:binding C._EVP_PKEY_ED25519
const EVP_PKEY_ED25519 = 1087

//cgo:binding C._EVP_PKEY_DSA
const EVP_PKEY_DSA = 116

//cgo:binding C._EVP_PKEY_OP_DERIVE
const EVP_PKEY_OP_DERIVE = (1 << 10)

//cgo:binding C._EVP_MAX_MD_SIZE
const EVP_MAX_MD_SIZE = 64

//cgo:binding C._EVP_PKEY_PUBLIC_KEY
const EVP_PKEY_PUBLIC_KEY = 0x86

//cgo:binding C._EVP_PKEY_KEYPAIR
const EVP_PKEY_KEYPAIR = 0x87

//cgo:binding C._EVP_MD_CTRL_XOF_LEN
const EVP_MD_CTRL_XOF_LEN = 0x3

//cgo:binding C._EVP_PKEY_CTRL_EC_PARAMGEN_CURVE_NID
const EVP_PKEY_CTRL_EC_PARAMGEN_CURVE_NID = 0x1001

//cgo:binding C._EVP_KDF_HKDF_MODE_EXTRACT_ONLY
const EVP_KDF_HKDF_MODE_EXTRACT_ONLY = 1

//cgo:binding C._EVP_KDF_HKDF_MODE_EXPAND_ONLY
const EVP_KDF_HKDF_MODE_EXPAND_ONLY = 2

//cgo:binding C._EVP_PKEY_CTRL_TLS_MD
const EVP_PKEY_CTRL_TLS_MD = 0x1000

//cgo:binding C._EVP_PKEY_CTRL_TLS_SECRET
const EVP_PKEY_CTRL_TLS_SECRET = 0x1001

//cgo:binding C._EVP_PKEY_CTRL_TLS_SEED
const EVP_PKEY_CTRL_TLS_SEED = 0x1002

//cgo:binding C._EVP_PKEY_CTRL_HKDF_MD
const EVP_PKEY_CTRL_HKDF_MD = 0x1003

//cgo:binding C._EVP_PKEY_CTRL_HKDF_SALT
const EVP_PKEY_CTRL_HKDF_SALT = 0x1004

//cgo:binding C._EVP_PKEY_CTRL_HKDF_KEY
const EVP_PKEY_CTRL_HKDF_KEY = 0x1005

//cgo:binding C._EVP_PKEY_CTRL_HKDF_INFO
const EVP_PKEY_CTRL_HKDF_INFO = 0x1006

//cgo:binding C._EVP_PKEY_CTRL_HKDF_MODE
const EVP_PKEY_CTRL_HKDF_MODE = 0x1007

//cgo:binding C._NID_X9_62_prime256v1
const NID_X9_62_prime256v1 = 415

//cgo:binding C._NID_secp224r1
const NID_secp224r1 = 713

//cgo:binding C._NID_secp384r1
const NID_secp384r1 = 715

//cgo:binding C._NID_secp521r1
const NID_secp521r1 = 716

//cgo:binding C._RSA_PKCS1_PADDING
const RSA_PKCS1_PADDING = 1

//cgo:binding C._RSA_NO_PADDING
const RSA_NO_PADDING = 3

//cgo:binding C._RSA_PKCS1_OAEP_PADDING
const RSA_PKCS1_OAEP_PADDING = 4

//cgo:binding C._RSA_PKCS1_PSS_PADDING
const RSA_PKCS1_PSS_PADDING = 6

//cgo:binding C._RSA_PSS_SALTLEN_DIGEST
const RSA_PSS_SALTLEN_DIGEST = -1

//cgo:binding C._RSA_PSS_SALTLEN_AUTO
const RSA_PSS_SALTLEN_AUTO = -2

//cgo:binding C._RSA_PSS_SALTLEN_MAX_SIGN
const RSA_PSS_SALTLEN_MAX_SIGN = -2

//cgo:binding C._RSA_PSS_SALTLEN_MAX
const RSA_PSS_SALTLEN_MAX = -3

//cgo:binding C._EVP_PKEY_CTRL_RSA_PADDING
const EVP_PKEY_CTRL_RSA_PADDING = 0x1001

//cgo:binding C._EVP_PKEY_CTRL_RSA_PSS_SALTLEN
const EVP_PKEY_CTRL_RSA_PSS_SALTLEN = 0x1002

//cgo:binding C._EVP_PKEY_CTRL_RSA_KEYGEN_BITS
const EVP_PKEY_CTRL_RSA_KEYGEN_BITS = 0x1003

//cgo:binding C._EVP_PKEY_CTRL_RSA_MGF1_MD
const EVP_PKEY_CTRL_RSA_MGF1_MD = 0x1005

//cgo:binding C._EVP_PKEY_CTRL_RSA_OAEP_MD
const EVP_PKEY_CTRL_RSA_OAEP_MD = 0x1009

//cgo:binding C._EVP_PKEY_CTRL_RSA_OAEP_LABEL
const EVP_PKEY_CTRL_RSA_OAEP_LABEL = 0x100A

//cgo:binding C._EVP_PKEY_CTRL_DSA_PARAMGEN_BITS
const EVP_PKEY_CTRL_DSA_PARAMGEN_BITS = 0x1001

//cgo:binding C._EVP_PKEY_CTRL_DSA_PARAMGEN_Q_BITS
const EVP_PKEY_CTRL_DSA_PARAMGEN_Q_BITS = 0x1002

//cgo:binding C._OSSL_PARAM_INTEGER
const OSSL_PARAM_INTEGER = 1

//cgo:binding C._OSSL_PARAM_OCTET_STRING
const OSSL_PARAM_OCTET_STRING = 5

//cgo:binding C.BIO_CTRL_INFO
const BIO_CTRL_INFO = 3

//cgo:binding C.dlsym
func _mkcgo_dlsym_zossl(handle unsafe.Pointer, name *byte) unsafe.Pointer

type _mkcgo_func_BIO_ctrl uintptr

//cgo:funcptr
func (fp _mkcgo_func_BIO_ctrl) Call(p0 BIO_PTR, p1 int32, p2 int64, p3 unsafe.Pointer) int64

type _mkcgo_func_BIO_free uintptr

//cgo:funcptr
func (fp _mkcgo_func_BIO_free) Call(p0 BIO_PTR) int32

type _mkcgo_func_BIO_new uintptr

//cgo:funcptr
func (fp _mkcgo_func_BIO_new) Call(p0 BIO_METHOD_PTR) BIO_PTR

type _mkcgo_func_BIO_s_mem uintptr

//cgo:funcptr
func (fp _mkcgo_func_BIO_s_mem) Call() BIO_METHOD_PTR

type _mkcgo_func_BN_bin2bn uintptr

//cgo:funcptr
func (fp _mkcgo_func_BN_bin2bn) Call(p0 *byte, p1 int32, p2 BIGNUM_PTR) BIGNUM_PTR

type _mkcgo_func_BN_bn2binpad uintptr

//cgo:funcptr
func (fp _mkcgo_func_BN_bn2binpad) Call(p0 BIGNUM_PTR, p1 *byte, p2 int32) int32

type _mkcgo_func_BN_bn2lebinpad uintptr

//cgo:funcptr
func (fp _mkcgo_func_BN_bn2lebinpad) Call(p0 BIGNUM_PTR, p1 *byte, p2 int32) int32

type _mkcgo_func_BN_clear uintptr

//cgo:funcptr
func (fp _mkcgo_func_BN_clear) Call(p0 BIGNUM_PTR)

type _mkcgo_func_BN_clear_free uintptr

//cgo:funcptr
func (fp _mkcgo_func_BN_clear_free) Call(p0 BIGNUM_PTR)

type _mkcgo_func_BN_free uintptr

//cgo:funcptr
func (fp _mkcgo_func_BN_free) Call(p0 BIGNUM_PTR)

type _mkcgo_func_BN_lebin2bn uintptr

//cgo:funcptr
func (fp _mkcgo_func_BN_lebin2bn) Call(p0 *byte, p1 int32, p2 BIGNUM_PTR) BIGNUM_PTR

type _mkcgo_func_BN_new uintptr

//cgo:funcptr
func (fp _mkcgo_func_BN_new) Call() BIGNUM_PTR

type _mkcgo_func_BN_num_bits uintptr

//cgo:funcptr
func (fp _mkcgo_func_BN_num_bits) Call(p0 BIGNUM_PTR) int32

type _mkcgo_func_CRYPTO_free uintptr

//cgo:funcptr
func (fp _mkcgo_func_CRYPTO_free) Call(p0 unsafe.Pointer, p1 *byte, p2 int32)

type _mkcgo_func_CRYPTO_malloc uintptr

//cgo:funcptr
func (fp _mkcgo_func_CRYPTO_malloc) Call(p0 int, p1 *byte, p2 int32) unsafe.Pointer

type _mkcgo_func_DSA_free uintptr

//cgo:funcptr
func (fp _mkcgo_func_DSA_free) Call(p0 DSA_PTR)

type _mkcgo_func_DSA_generate_key uintptr

//cgo:funcptr
func (fp _mkcgo_func_DSA_generate_key) Call(p0 DSA_PTR) int32

type _mkcgo_func_DSA_get0_key uintptr

//cgo:funcptr
func (fp _mkcgo_func_DSA_get0_key) Call(p0 DSA_PTR, p1 *BIGNUM_PTR, p2 *BIGNUM_PTR)

type _mkcgo_func_DSA_get0_pqg uintptr

//cgo:funcptr
func (fp _mkcgo_func_DSA_get0_pqg) Call(p0 DSA_PTR, p1 *BIGNUM_PTR, p2 *BIGNUM_PTR, p3 *BIGNUM_PTR)

type _mkcgo_func_DSA_new uintptr

//cgo:funcptr
func (fp _mkcgo_func_DSA_new) Call() DSA_PTR

type _mkcgo_func_DSA_set0_key uintptr

//cgo:funcptr
func (fp _mkcgo_func_DSA_set0_key) Call(p0 DSA_PTR, p1 BIGNUM_PTR, p2 BIGNUM_PTR) int32

type _mkcgo_func_DSA_set0_pqg uintptr

//cgo:funcptr
func (fp _mkcgo_func_DSA_set0_pqg) Call(p0 DSA_PTR, p1 BIGNUM_PTR, p2 BIGNUM_PTR, p3 BIGNUM_PTR) int32

type _mkcgo_func_EC_GROUP_free uintptr

//cgo:funcptr
func (fp _mkcgo_func_EC_GROUP_free) Call(p0 EC_GROUP_PTR)

type _mkcgo_func_EC_GROUP_new_by_curve_name uintptr

//cgo:funcptr
func (fp _mkcgo_func_EC_GROUP_new_by_curve_name) Call(p0 int32) EC_GROUP_PTR

type _mkcgo_func_EC_KEY_check_key uintptr

//cgo:funcptr
func (fp _mkcgo_func_EC_KEY_check_key) Call(p0 EC_KEY_PTR) int32

type _mkcgo_func_EC_KEY_free uintptr

//cgo:funcptr
func (fp _mkcgo_func_EC_KEY_free) Call(p0 EC_KEY_PTR)

type _mkcgo_func_EC_KEY_get0_group uintptr

//cgo:funcptr
func (fp _mkcgo_func_EC_KEY_get0_group) Call(p0 EC_KEY_PTR) EC_GROUP_PTR

type _mkcgo_func_EC_KEY_get0_private_key uintptr

//cgo:funcptr
func (fp _mkcgo_func_EC_KEY_get0_private_key) Call(p0 EC_KEY_PTR) BIGNUM_PTR

type _mkcgo_func_EC_KEY_get0_public_key uintptr

//cgo:funcptr
func (fp _mkcgo_func_EC_KEY_get0_public_key) Call(p0 EC_KEY_PTR) EC_POINT_PTR

type _mkcgo_func_EC_KEY_new_by_curve_name uintptr

//cgo:funcptr
func (fp _mkcgo_func_EC_KEY_new_by_curve_name) Call(p0 int32) EC_KEY_PTR

type _mkcgo_func_EC_KEY_set_private_key uintptr

//cgo:funcptr
func (fp _mkcgo_func_EC_KEY_set_private_key) Call(p0 EC_KEY_PTR, p1 BIGNUM_PTR) int32

type _mkcgo_func_EC_KEY_set_public_key uintptr

//cgo:funcptr
func (fp _mkcgo_func_EC_KEY_set_public_key) Call(p0 EC_KEY_PTR, p1 EC_POINT_PTR) int32

type _mkcgo_func_EC_KEY_set_public_key_affine_coordinates uintptr

//cgo:funcptr
func (fp _mkcgo_func_EC_KEY_set_public_key_affine_coordinates) Call(p0 EC_KEY_PTR, p1 BIGNUM_PTR, p2 BIGNUM_PTR) int32

type _mkcgo_func_EC_POINT_free uintptr

//cgo:funcptr
func (fp _mkcgo_func_EC_POINT_free) Call(p0 EC_POINT_PTR)

type _mkcgo_func_EC_POINT_get_affine_coordinates_GFp uintptr

//cgo:funcptr
func (fp _mkcgo_func_EC_POINT_get_affine_coordinates_GFp) Call(p0 EC_GROUP_PTR, p1 EC_POINT_PTR, p2 BIGNUM_PTR, p3 BIGNUM_PTR, p4 BN_CTX_PTR) int32

type _mkcgo_func_EC_POINT_mul uintptr

//cgo:funcptr
func (fp _mkcgo_func_EC_POINT_mul) Call(p0 EC_GROUP_PTR, p1 EC_POINT_PTR, p2 BIGNUM_PTR, p3 EC_POINT_PTR, p4 BIGNUM_PTR, p5 BN_CTX_PTR) int32

type _mkcgo_func_EC_POINT_new uintptr

//cgo:funcptr
func (fp _mkcgo_func_EC_POINT_new) Call(p0 EC_GROUP_PTR) EC_POINT_PTR

type _mkcgo_func_EC_POINT_oct2point uintptr

//cgo:funcptr
func (fp _mkcgo_func_EC_POINT_oct2point) Call(p0 EC_GROUP_PTR, p1 EC_POINT_PTR, p2 *byte, p3 int, p4 BN_CTX_PTR) int32

type _mkcgo_func_EC_POINT_point2oct uintptr

//cgo:funcptr
func (fp _mkcgo_func_EC_POINT_point2oct) Call(p0 EC_GROUP_PTR, p1 EC_POINT_PTR, p2 Point_conversion_form_t, p3 *byte, p4 int, p5 BN_CTX_PTR) int

type _mkcgo_func_EC_POINT_set_affine_coordinates uintptr

//cgo:funcptr
func (fp _mkcgo_func_EC_POINT_set_affine_coordinates) Call(p0 EC_GROUP_PTR, p1 EC_POINT_PTR, p2 BIGNUM_PTR, p3 BIGNUM_PTR, p4 BN_CTX_PTR) int32

type _mkcgo_func_ERR_peek_error uintptr

//cgo:funcptr
func (fp _mkcgo_func_ERR_peek_error) Call() uint64

type _mkcgo_func_ERR_print_errors uintptr

//cgo:funcptr
func (fp _mkcgo_func_ERR_print_errors) Call(p0 BIO_PTR)

type _mkcgo_func_EVP_CIPHER_CTX_ctrl uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_CIPHER_CTX_ctrl) Call(p0 EVP_CIPHER_CTX_PTR, p1 int32, p2 int32, p3 unsafe.Pointer) int32

type _mkcgo_func_EVP_CIPHER_CTX_free uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_CIPHER_CTX_free) Call(p0 EVP_CIPHER_CTX_PTR)

type _mkcgo_func_EVP_CIPHER_CTX_new uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_CIPHER_CTX_new) Call() EVP_CIPHER_CTX_PTR

type _mkcgo_func_EVP_CIPHER_CTX_set_key_length uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_CIPHER_CTX_set_key_length) Call(p0 EVP_CIPHER_CTX_PTR, p1 int32) int32

type _mkcgo_func_EVP_CIPHER_CTX_set_padding uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_CIPHER_CTX_set_padding) Call(p0 EVP_CIPHER_CTX_PTR, p1 int32) int32

type _mkcgo_func_EVP_CIPHER_fetch uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_CIPHER_fetch) Call(p0 OSSL_LIB_CTX_PTR, p1 *byte, p2 *byte) EVP_CIPHER_PTR

type _mkcgo_func_EVP_CIPHER_get0_name uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_CIPHER_get0_name) Call(p0 EVP_CIPHER_PTR) *byte

type _mkcgo_func_EVP_CIPHER_get_block_size uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_CIPHER_get_block_size) Call(p0 EVP_CIPHER_PTR) int32

type _mkcgo_func_EVP_CipherInit_ex uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_CipherInit_ex) Call(p0 EVP_CIPHER_CTX_PTR, p1 EVP_CIPHER_PTR, p2 ENGINE_PTR, p3 *byte, p4 *byte, p5 int32) int32

type _mkcgo_func_EVP_CipherInit_ex2 uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_CipherInit_ex2) Call(p0 EVP_CIPHER_CTX_PTR, p1 EVP_CIPHER_PTR, p2 *byte, p3 *byte, p4 int32, p5 OSSL_PARAM_PTR) int32

type _mkcgo_func_EVP_CipherUpdate uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_CipherUpdate) Call(p0 EVP_CIPHER_CTX_PTR, p1 *byte, p2 *int32, p3 *byte, p4 int32) int32

type _mkcgo_func_EVP_DecryptFinal_ex uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_DecryptFinal_ex) Call(p0 EVP_CIPHER_CTX_PTR, p1 *byte, p2 *int32) int32

type _mkcgo_func_EVP_DecryptInit_ex uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_DecryptInit_ex) Call(p0 EVP_CIPHER_CTX_PTR, p1 EVP_CIPHER_PTR, p2 ENGINE_PTR, p3 *byte, p4 *byte) int32

type _mkcgo_func_EVP_DecryptUpdate uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_DecryptUpdate) Call(p0 EVP_CIPHER_CTX_PTR, p1 *byte, p2 *int32, p3 *byte, p4 int32) int32

type _mkcgo_func_EVP_Digest uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_Digest) Call(p0 unsafe.Pointer, p1 int, p2 *byte, p3 *uint32, p4 EVP_MD_PTR, p5 ENGINE_PTR) int32

type _mkcgo_func_EVP_DigestFinalXOF uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_DigestFinalXOF) Call(p0 EVP_MD_CTX_PTR, p1 *byte, p2 int) int32

type _mkcgo_func_EVP_DigestFinal_ex uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_DigestFinal_ex) Call(p0 EVP_MD_CTX_PTR, p1 *byte, p2 *uint32) int32

type _mkcgo_func_EVP_DigestInit uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_DigestInit) Call(p0 EVP_MD_CTX_PTR, p1 EVP_MD_PTR) int32

type _mkcgo_func_EVP_DigestInit_ex uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_DigestInit_ex) Call(p0 EVP_MD_CTX_PTR, p1 EVP_MD_PTR, p2 ENGINE_PTR) int32

type _mkcgo_func_EVP_DigestSign uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_DigestSign) Call(p0 EVP_MD_CTX_PTR, p1 *byte, p2 *int, p3 *byte, p4 int) int32

type _mkcgo_func_EVP_DigestSignFinal uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_DigestSignFinal) Call(p0 EVP_MD_CTX_PTR, p1 *byte, p2 *int) int32

type _mkcgo_func_EVP_DigestSignInit uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_DigestSignInit) Call(p0 EVP_MD_CTX_PTR, p1 *EVP_PKEY_CTX_PTR, p2 EVP_MD_PTR, p3 ENGINE_PTR, p4 EVP_PKEY_PTR) int32

type _mkcgo_func_EVP_DigestSqueeze uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_DigestSqueeze) Call(p0 EVP_MD_CTX_PTR, p1 *byte, p2 int) int32

type _mkcgo_func_EVP_DigestUpdate uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_DigestUpdate) Call(p0 EVP_MD_CTX_PTR, p1 unsafe.Pointer, p2 int) int32

type _mkcgo_func_EVP_DigestVerify uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_DigestVerify) Call(p0 EVP_MD_CTX_PTR, p1 *byte, p2 int, p3 *byte, p4 int) int32

type _mkcgo_func_EVP_DigestVerifyFinal uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_DigestVerifyFinal) Call(p0 EVP_MD_CTX_PTR, p1 *byte, p2 int) int32

type _mkcgo_func_EVP_DigestVerifyInit uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_DigestVerifyInit) Call(p0 EVP_MD_CTX_PTR, p1 *EVP_PKEY_CTX_PTR, p2 EVP_MD_PTR, p3 ENGINE_PTR, p4 EVP_PKEY_PTR) int32

type _mkcgo_func_EVP_EncryptFinal_ex uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_EncryptFinal_ex) Call(p0 EVP_CIPHER_CTX_PTR, p1 *byte, p2 *int32) int32

type _mkcgo_func_EVP_EncryptInit_ex uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_EncryptInit_ex) Call(p0 EVP_CIPHER_CTX_PTR, p1 EVP_CIPHER_PTR, p2 ENGINE_PTR, p3 *byte, p4 *byte) int32

type _mkcgo_func_EVP_EncryptUpdate uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_EncryptUpdate) Call(p0 EVP_CIPHER_CTX_PTR, p1 *byte, p2 *int32, p3 *byte, p4 int32) int32

type _mkcgo_func_EVP_KDF_CTX_free uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_KDF_CTX_free) Call(p0 EVP_KDF_CTX_PTR)

type _mkcgo_func_EVP_KDF_CTX_get_kdf_size uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_KDF_CTX_get_kdf_size) Call(p0 EVP_KDF_CTX_PTR) int

type _mkcgo_func_EVP_KDF_CTX_new uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_KDF_CTX_new) Call(p0 EVP_KDF_PTR) EVP_KDF_CTX_PTR

type _mkcgo_func_EVP_KDF_CTX_set_params uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_KDF_CTX_set_params) Call(p0 EVP_KDF_CTX_PTR, p1 OSSL_PARAM_PTR) int32

type _mkcgo_func_EVP_KDF_derive uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_KDF_derive) Call(p0 EVP_KDF_CTX_PTR, p1 *byte, p2 int, p3 OSSL_PARAM_PTR) int32

type _mkcgo_func_EVP_KDF_fetch uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_KDF_fetch) Call(p0 OSSL_LIB_CTX_PTR, p1 *byte, p2 *byte) EVP_KDF_PTR

type _mkcgo_func_EVP_KDF_free uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_KDF_free) Call(p0 EVP_KDF_PTR)

type _mkcgo_func_EVP_KEYMGMT_fetch uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_KEYMGMT_fetch) Call(p0 OSSL_LIB_CTX_PTR, p1 *byte, p2 *byte) EVP_KEYMGMT_PTR

type _mkcgo_func_EVP_KEYMGMT_free uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_KEYMGMT_free) Call(p0 EVP_KEYMGMT_PTR)

type _mkcgo_func_EVP_MAC_CTX_dup uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_MAC_CTX_dup) Call(p0 EVP_MAC_CTX_PTR) EVP_MAC_CTX_PTR

type _mkcgo_func_EVP_MAC_CTX_free uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_MAC_CTX_free) Call(p0 EVP_MAC_CTX_PTR)

type _mkcgo_func_EVP_MAC_CTX_new uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_MAC_CTX_new) Call(p0 EVP_MAC_PTR) EVP_MAC_CTX_PTR

type _mkcgo_func_EVP_MAC_CTX_set_params uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_MAC_CTX_set_params) Call(p0 EVP_MAC_CTX_PTR, p1 OSSL_PARAM_PTR) int32

type _mkcgo_func_EVP_MAC_fetch uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_MAC_fetch) Call(p0 OSSL_LIB_CTX_PTR, p1 *byte, p2 *byte) EVP_MAC_PTR

type _mkcgo_func_EVP_MAC_final uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_MAC_final) Call(p0 EVP_MAC_CTX_PTR, p1 *byte, p2 *int, p3 int) int32

type _mkcgo_func_EVP_MAC_init uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_MAC_init) Call(p0 EVP_MAC_CTX_PTR, p1 *byte, p2 int, p3 OSSL_PARAM_PTR) int32

type _mkcgo_func_EVP_MAC_update uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_MAC_update) Call(p0 EVP_MAC_CTX_PTR, p1 *byte, p2 int) int32

type _mkcgo_func_EVP_MD_CTX_copy_ex uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_MD_CTX_copy_ex) Call(p0 EVP_MD_CTX_PTR, p1 EVP_MD_CTX_PTR) int32

type _mkcgo_func_EVP_MD_CTX_ctrl uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_MD_CTX_ctrl) Call(p0 EVP_MD_CTX_PTR, p1 int32, p2 int32, p3 unsafe.Pointer) int32

type _mkcgo_func_EVP_MD_CTX_free uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_MD_CTX_free) Call(p0 EVP_MD_CTX_PTR)

type _mkcgo_func_EVP_MD_CTX_get_params uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_MD_CTX_get_params) Call(p0 EVP_MD_CTX_PTR, p1 OSSL_PARAM_PTR) int32

type _mkcgo_func_EVP_MD_CTX_gettable_params uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_MD_CTX_gettable_params) Call(p0 EVP_MD_CTX_PTR) OSSL_PARAM_PTR

type _mkcgo_func_EVP_MD_CTX_new uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_MD_CTX_new) Call() EVP_MD_CTX_PTR

type _mkcgo_func_EVP_MD_CTX_set_params uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_MD_CTX_set_params) Call(p0 EVP_MD_CTX_PTR, p1 OSSL_PARAM_PTR) int32

type _mkcgo_func_EVP_MD_CTX_settable_params uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_MD_CTX_settable_params) Call(p0 EVP_MD_CTX_PTR) OSSL_PARAM_PTR

type _mkcgo_func_EVP_MD_fetch uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_MD_fetch) Call(p0 OSSL_LIB_CTX_PTR, p1 *byte, p2 *byte) EVP_MD_PTR

type _mkcgo_func_EVP_MD_free uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_MD_free) Call(p0 EVP_MD_PTR)

type _mkcgo_func_EVP_MD_get0_name uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_MD_get0_name) Call(p0 EVP_MD_PTR) *byte

type _mkcgo_func_EVP_MD_get0_provider uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_MD_get0_provider) Call(p0 EVP_MD_PTR) OSSL_PROVIDER_PTR

type _mkcgo_func_EVP_MD_get_block_size uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_MD_get_block_size) Call(p0 EVP_MD_PTR) int32

type _mkcgo_func_EVP_MD_get_size uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_MD_get_size) Call(p0 EVP_MD_PTR) int32

type _mkcgo_func_EVP_MD_get_type uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_MD_get_type) Call(p0 EVP_MD_PTR) int32

type _mkcgo_func_EVP_PKEY_CTX_add1_hkdf_info uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_CTX_add1_hkdf_info) Call(p0 EVP_PKEY_CTX_PTR, p1 *byte, p2 int32) int32

type _mkcgo_func_EVP_PKEY_CTX_ctrl uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_CTX_ctrl) Call(p0 EVP_PKEY_CTX_PTR, p1 int32, p2 int32, p3 int32, p4 int32, p5 unsafe.Pointer) int32

type _mkcgo_func_EVP_PKEY_CTX_free uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_CTX_free) Call(p0 EVP_PKEY_CTX_PTR)

type _mkcgo_func_EVP_PKEY_CTX_new uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_CTX_new) Call(p0 EVP_PKEY_PTR, p1 ENGINE_PTR) EVP_PKEY_CTX_PTR

type _mkcgo_func_EVP_PKEY_CTX_new_from_name uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_CTX_new_from_name) Call(p0 OSSL_LIB_CTX_PTR, p1 *byte, p2 *byte) EVP_PKEY_CTX_PTR

type _mkcgo_func_EVP_PKEY_CTX_new_from_pkey uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_CTX_new_from_pkey) Call(p0 OSSL_LIB_CTX_PTR, p1 EVP_PKEY_PTR, p2 *byte) EVP_PKEY_CTX_PTR

type _mkcgo_func_EVP_PKEY_CTX_new_id uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_CTX_new_id) Call(p0 int32, p1 ENGINE_PTR) EVP_PKEY_CTX_PTR

type _mkcgo_func_EVP_PKEY_CTX_set0_rsa_oaep_label uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_CTX_set0_rsa_oaep_label) Call(p0 EVP_PKEY_CTX_PTR, p1 unsafe.Pointer, p2 int32) int32

type _mkcgo_func_EVP_PKEY_CTX_set1_hkdf_key uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_CTX_set1_hkdf_key) Call(p0 EVP_PKEY_CTX_PTR, p1 *byte, p2 int32) int32

type _mkcgo_func_EVP_PKEY_CTX_set1_hkdf_salt uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_CTX_set1_hkdf_salt) Call(p0 EVP_PKEY_CTX_PTR, p1 *byte, p2 int32) int32

type _mkcgo_func_EVP_PKEY_CTX_set_hkdf_md uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_CTX_set_hkdf_md) Call(p0 EVP_PKEY_CTX_PTR, p1 EVP_MD_PTR) int32

type _mkcgo_func_EVP_PKEY_CTX_set_hkdf_mode uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_CTX_set_hkdf_mode) Call(p0 EVP_PKEY_CTX_PTR, p1 int32) int32

type _mkcgo_func_EVP_PKEY_CTX_set_params uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_CTX_set_params) Call(p0 EVP_PKEY_CTX_PTR, p1 OSSL_PARAM_PTR) int32

type _mkcgo_func_EVP_PKEY_Q_keygen_EC uintptr

//cgo:variadic 3
//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_Q_keygen_EC) Call(p0 OSSL_LIB_CTX_PTR, p1 *byte, p2 *byte, p3 *byte) EVP_PKEY_PTR

type _mkcgo_func_EVP_PKEY_Q_keygen_ED25519 uintptr

//cgo:variadic 3
//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_Q_keygen_ED25519) Call(p0 OSSL_LIB_CTX_PTR, p1 *byte, p2 *byte) EVP_PKEY_PTR

type _mkcgo_func_EVP_PKEY_Q_keygen_MLDSA uintptr

//cgo:variadic 3
//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_Q_keygen_MLDSA) Call(p0 OSSL_LIB_CTX_PTR, p1 *byte, p2 *byte) EVP_PKEY_PTR

type _mkcgo_func_EVP_PKEY_Q_keygen_MLKEM uintptr

//cgo:variadic 3
//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_Q_keygen_MLKEM) Call(p0 OSSL_LIB_CTX_PTR, p1 *byte, p2 *byte) EVP_PKEY_PTR

type _mkcgo_func_EVP_PKEY_Q_keygen_RSA uintptr

//cgo:variadic 3
//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_Q_keygen_RSA) Call(p0 OSSL_LIB_CTX_PTR, p1 *byte, p2 *byte, p3 int) EVP_PKEY_PTR

type _mkcgo_func_EVP_PKEY_Q_keygen_X25519 uintptr

//cgo:variadic 3
//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_Q_keygen_X25519) Call(p0 OSSL_LIB_CTX_PTR, p1 *byte, p2 *byte) EVP_PKEY_PTR

type _mkcgo_func_EVP_PKEY_assign uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_assign) Call(p0 EVP_PKEY_PTR, p1 int32, p2 unsafe.Pointer) int32

type _mkcgo_func_EVP_PKEY_decapsulate uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_decapsulate) Call(p0 EVP_PKEY_CTX_PTR, p1 *byte, p2 *int, p3 *byte, p4 int) int32

type _mkcgo_func_EVP_PKEY_decapsulate_init uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_decapsulate_init) Call(p0 EVP_PKEY_CTX_PTR, p1 OSSL_PARAM_PTR) int32

type _mkcgo_func_EVP_PKEY_decrypt uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_decrypt) Call(p0 EVP_PKEY_CTX_PTR, p1 *byte, p2 *int, p3 *byte, p4 int) int32

type _mkcgo_func_EVP_PKEY_decrypt_init uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_decrypt_init) Call(p0 EVP_PKEY_CTX_PTR) int32

type _mkcgo_func_EVP_PKEY_derive uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_derive) Call(p0 EVP_PKEY_CTX_PTR, p1 *byte, p2 *int) int32

type _mkcgo_func_EVP_PKEY_derive_init uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_derive_init) Call(p0 EVP_PKEY_CTX_PTR) int32

type _mkcgo_func_EVP_PKEY_derive_set_peer uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_derive_set_peer) Call(p0 EVP_PKEY_CTX_PTR, p1 EVP_PKEY_PTR) int32

type _mkcgo_func_EVP_PKEY_encapsulate uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_encapsulate) Call(p0 EVP_PKEY_CTX_PTR, p1 *byte, p2 *int, p3 *byte, p4 *int) int32

type _mkcgo_func_EVP_PKEY_encapsulate_init uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_encapsulate_init) Call(p0 EVP_PKEY_CTX_PTR, p1 OSSL_PARAM_PTR) int32

type _mkcgo_func_EVP_PKEY_encrypt uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_encrypt) Call(p0 EVP_PKEY_CTX_PTR, p1 *byte, p2 *int, p3 *byte, p4 int) int32

type _mkcgo_func_EVP_PKEY_encrypt_init uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_encrypt_init) Call(p0 EVP_PKEY_CTX_PTR) int32

type _mkcgo_func_EVP_PKEY_eq uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_eq) Call(p0 EVP_PKEY_PTR, p1 EVP_PKEY_PTR) int32

type _mkcgo_func_EVP_PKEY_free uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_free) Call(p0 EVP_PKEY_PTR)

type _mkcgo_func_EVP_PKEY_fromdata uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_fromdata) Call(p0 EVP_PKEY_CTX_PTR, p1 *EVP_PKEY_PTR, p2 int32, p3 OSSL_PARAM_PTR) int32

type _mkcgo_func_EVP_PKEY_fromdata_init uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_fromdata_init) Call(p0 EVP_PKEY_CTX_PTR) int32

type _mkcgo_func_EVP_PKEY_get0_DSA uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_get0_DSA) Call(p0 EVP_PKEY_PTR) DSA_PTR

type _mkcgo_func_EVP_PKEY_get0_EC_KEY uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_get0_EC_KEY) Call(p0 EVP_PKEY_PTR) EC_KEY_PTR

type _mkcgo_func_EVP_PKEY_get1_RSA uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_get1_RSA) Call(p0 EVP_PKEY_PTR) RSA_PTR

type _mkcgo_func_EVP_PKEY_get1_encoded_public_key uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_get1_encoded_public_key) Call(p0 EVP_PKEY_PTR, p1 **byte) int

type _mkcgo_func_EVP_PKEY_get_bits uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_get_bits) Call(p0 EVP_PKEY_PTR) int32

type _mkcgo_func_EVP_PKEY_get_bn_param uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_get_bn_param) Call(p0 EVP_PKEY_PTR, p1 *byte, p2 *BIGNUM_PTR) int32

type _mkcgo_func_EVP_PKEY_get_octet_string_param uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_get_octet_string_param) Call(p0 EVP_PKEY_PTR, p1 *byte, p2 *byte, p3 int, p4 *int) int32

type _mkcgo_func_EVP_PKEY_get_raw_private_key uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_get_raw_private_key) Call(p0 EVP_PKEY_PTR, p1 *byte, p2 *int) int32

type _mkcgo_func_EVP_PKEY_get_raw_public_key uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_get_raw_public_key) Call(p0 EVP_PKEY_PTR, p1 *byte, p2 *int) int32

type _mkcgo_func_EVP_PKEY_get_size uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_get_size) Call(p0 EVP_PKEY_PTR) int32

type _mkcgo_func_EVP_PKEY_keygen uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_keygen) Call(p0 EVP_PKEY_CTX_PTR, p1 *EVP_PKEY_PTR) int32

type _mkcgo_func_EVP_PKEY_keygen_init uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_keygen_init) Call(p0 EVP_PKEY_CTX_PTR) int32

type _mkcgo_func_EVP_PKEY_new uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_new) Call() EVP_PKEY_PTR

type _mkcgo_func_EVP_PKEY_new_raw_private_key uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_new_raw_private_key) Call(p0 int32, p1 ENGINE_PTR, p2 *byte, p3 int) EVP_PKEY_PTR

type _mkcgo_func_EVP_PKEY_new_raw_public_key uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_new_raw_public_key) Call(p0 int32, p1 ENGINE_PTR, p2 *byte, p3 int) EVP_PKEY_PTR

type _mkcgo_func_EVP_PKEY_paramgen uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_paramgen) Call(p0 EVP_PKEY_CTX_PTR, p1 *EVP_PKEY_PTR) int32

type _mkcgo_func_EVP_PKEY_paramgen_init uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_paramgen_init) Call(p0 EVP_PKEY_CTX_PTR) int32

type _mkcgo_func_EVP_PKEY_private_check uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_private_check) Call(p0 EVP_PKEY_CTX_PTR) int32

type _mkcgo_func_EVP_PKEY_public_check_quick uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_public_check_quick) Call(p0 EVP_PKEY_CTX_PTR) int32

type _mkcgo_func_EVP_PKEY_set1_EC_KEY uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_set1_EC_KEY) Call(p0 EVP_PKEY_PTR, p1 EC_KEY_PTR) int32

type _mkcgo_func_EVP_PKEY_set1_encoded_public_key uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_set1_encoded_public_key) Call(p0 EVP_PKEY_PTR, p1 *byte, p2 int) int32

type _mkcgo_func_EVP_PKEY_sign uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_sign) Call(p0 EVP_PKEY_CTX_PTR, p1 *byte, p2 *int, p3 *byte, p4 int) int32

type _mkcgo_func_EVP_PKEY_sign_init uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_sign_init) Call(p0 EVP_PKEY_CTX_PTR) int32

type _mkcgo_func_EVP_PKEY_up_ref uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_up_ref) Call(p0 EVP_PKEY_PTR) int32

type _mkcgo_func_EVP_PKEY_verify uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_verify) Call(p0 EVP_PKEY_CTX_PTR, p1 *byte, p2 int, p3 *byte, p4 int) int32

type _mkcgo_func_EVP_PKEY_verify_init uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_PKEY_verify_init) Call(p0 EVP_PKEY_CTX_PTR) int32

type _mkcgo_func_EVP_SIGNATURE_fetch uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_SIGNATURE_fetch) Call(p0 OSSL_LIB_CTX_PTR, p1 *byte, p2 *byte) EVP_SIGNATURE_PTR

type _mkcgo_func_EVP_SIGNATURE_free uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_SIGNATURE_free) Call(p0 EVP_SIGNATURE_PTR)

type _mkcgo_func_EVP_aes_128_cbc uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_aes_128_cbc) Call() EVP_CIPHER_PTR

type _mkcgo_func_EVP_aes_128_ctr uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_aes_128_ctr) Call() EVP_CIPHER_PTR

type _mkcgo_func_EVP_aes_128_ecb uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_aes_128_ecb) Call() EVP_CIPHER_PTR

type _mkcgo_func_EVP_aes_128_gcm uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_aes_128_gcm) Call() EVP_CIPHER_PTR

type _mkcgo_func_EVP_aes_192_cbc uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_aes_192_cbc) Call() EVP_CIPHER_PTR

type _mkcgo_func_EVP_aes_192_ctr uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_aes_192_ctr) Call() EVP_CIPHER_PTR

type _mkcgo_func_EVP_aes_192_ecb uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_aes_192_ecb) Call() EVP_CIPHER_PTR

type _mkcgo_func_EVP_aes_192_gcm uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_aes_192_gcm) Call() EVP_CIPHER_PTR

type _mkcgo_func_EVP_aes_256_cbc uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_aes_256_cbc) Call() EVP_CIPHER_PTR

type _mkcgo_func_EVP_aes_256_ctr uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_aes_256_ctr) Call() EVP_CIPHER_PTR

type _mkcgo_func_EVP_aes_256_ecb uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_aes_256_ecb) Call() EVP_CIPHER_PTR

type _mkcgo_func_EVP_aes_256_gcm uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_aes_256_gcm) Call() EVP_CIPHER_PTR

type _mkcgo_func_EVP_chacha20_poly1305 uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_chacha20_poly1305) Call() EVP_CIPHER_PTR

type _mkcgo_func_EVP_default_properties_enable_fips uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_default_properties_enable_fips) Call(p0 OSSL_LIB_CTX_PTR, p1 int32) int32

type _mkcgo_func_EVP_default_properties_is_fips_enabled uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_default_properties_is_fips_enabled) Call(p0 OSSL_LIB_CTX_PTR) int32

type _mkcgo_func_EVP_des_cbc uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_des_cbc) Call() EVP_CIPHER_PTR

type _mkcgo_func_EVP_des_ecb uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_des_ecb) Call() EVP_CIPHER_PTR

type _mkcgo_func_EVP_des_ede3_cbc uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_des_ede3_cbc) Call() EVP_CIPHER_PTR

type _mkcgo_func_EVP_des_ede3_ecb uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_des_ede3_ecb) Call() EVP_CIPHER_PTR

type _mkcgo_func_EVP_md4 uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_md4) Call() EVP_MD_PTR

type _mkcgo_func_EVP_md5 uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_md5) Call() EVP_MD_PTR

type _mkcgo_func_EVP_md5_sha1 uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_md5_sha1) Call() EVP_MD_PTR

type _mkcgo_func_EVP_rc4 uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_rc4) Call() EVP_CIPHER_PTR

type _mkcgo_func_EVP_ripemd160 uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_ripemd160) Call() EVP_MD_PTR

type _mkcgo_func_EVP_sha1 uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_sha1) Call() EVP_MD_PTR

type _mkcgo_func_EVP_sha224 uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_sha224) Call() EVP_MD_PTR

type _mkcgo_func_EVP_sha256 uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_sha256) Call() EVP_MD_PTR

type _mkcgo_func_EVP_sha384 uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_sha384) Call() EVP_MD_PTR

type _mkcgo_func_EVP_sha3_224 uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_sha3_224) Call() EVP_MD_PTR

type _mkcgo_func_EVP_sha3_256 uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_sha3_256) Call() EVP_MD_PTR

type _mkcgo_func_EVP_sha3_384 uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_sha3_384) Call() EVP_MD_PTR

type _mkcgo_func_EVP_sha3_512 uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_sha3_512) Call() EVP_MD_PTR

type _mkcgo_func_EVP_sha512 uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_sha512) Call() EVP_MD_PTR

type _mkcgo_func_EVP_sha512_224 uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_sha512_224) Call() EVP_MD_PTR

type _mkcgo_func_EVP_sha512_256 uintptr

//cgo:funcptr
func (fp _mkcgo_func_EVP_sha512_256) Call() EVP_MD_PTR

type _mkcgo_func_FIPS_mode uintptr

//cgo:funcptr
func (fp _mkcgo_func_FIPS_mode) Call() int32

type _mkcgo_func_FIPS_mode_set uintptr

//cgo:funcptr
func (fp _mkcgo_func_FIPS_mode_set) Call(p0 int32) int32

type _mkcgo_func_HMAC_CTX_copy uintptr

//cgo:funcptr
func (fp _mkcgo_func_HMAC_CTX_copy) Call(p0 HMAC_CTX_PTR, p1 HMAC_CTX_PTR) int32

type _mkcgo_func_HMAC_CTX_free uintptr

//cgo:funcptr
func (fp _mkcgo_func_HMAC_CTX_free) Call(p0 HMAC_CTX_PTR)

type _mkcgo_func_HMAC_CTX_new uintptr

//cgo:funcptr
func (fp _mkcgo_func_HMAC_CTX_new) Call() HMAC_CTX_PTR

type _mkcgo_func_HMAC_Final uintptr

//cgo:funcptr
func (fp _mkcgo_func_HMAC_Final) Call(p0 HMAC_CTX_PTR, p1 *byte, p2 *uint32) int32

type _mkcgo_func_HMAC_Init_ex uintptr

//cgo:funcptr
func (fp _mkcgo_func_HMAC_Init_ex) Call(p0 HMAC_CTX_PTR, p1 unsafe.Pointer, p2 int32, p3 EVP_MD_PTR, p4 ENGINE_PTR) int32

type _mkcgo_func_HMAC_Update uintptr

//cgo:funcptr
func (fp _mkcgo_func_HMAC_Update) Call(p0 HMAC_CTX_PTR, p1 *byte, p2 int) int32

type _mkcgo_func_OBJ_nid2sn uintptr

//cgo:funcptr
func (fp _mkcgo_func_OBJ_nid2sn) Call(p0 int32) *byte

type _mkcgo_func_OPENSSL_init uintptr

//cgo:funcptr
func (fp _mkcgo_func_OPENSSL_init) Call()

type _mkcgo_func_OPENSSL_init_crypto uintptr

//cgo:funcptr
func (fp _mkcgo_func_OPENSSL_init_crypto) Call(p0 uint64, p1 OPENSSL_INIT_SETTINGS_PTR) int32

type _mkcgo_func_OPENSSL_version_major uintptr

//cgo:funcptr
func (fp _mkcgo_func_OPENSSL_version_major) Call() uint32

type _mkcgo_func_OPENSSL_version_minor uintptr

//cgo:funcptr
func (fp _mkcgo_func_OPENSSL_version_minor) Call() uint32

type _mkcgo_func_OPENSSL_version_patch uintptr

//cgo:funcptr
func (fp _mkcgo_func_OPENSSL_version_patch) Call() uint32

type _mkcgo_func_OSSL_PARAM_BLD_free uintptr

//cgo:funcptr
func (fp _mkcgo_func_OSSL_PARAM_BLD_free) Call(p0 OSSL_PARAM_BLD_PTR)

type _mkcgo_func_OSSL_PARAM_BLD_new uintptr

//cgo:funcptr
func (fp _mkcgo_func_OSSL_PARAM_BLD_new) Call() OSSL_PARAM_BLD_PTR

type _mkcgo_func_OSSL_PARAM_BLD_push_BN uintptr

//cgo:funcptr
func (fp _mkcgo_func_OSSL_PARAM_BLD_push_BN) Call(p0 OSSL_PARAM_BLD_PTR, p1 *byte, p2 BIGNUM_PTR) int32

type _mkcgo_func_OSSL_PARAM_BLD_push_int32 uintptr

//cgo:funcptr
func (fp _mkcgo_func_OSSL_PARAM_BLD_push_int32) Call(p0 OSSL_PARAM_BLD_PTR, p1 *byte, p2 int32) int32

type _mkcgo_func_OSSL_PARAM_BLD_push_octet_string uintptr

//cgo:funcptr
func (fp _mkcgo_func_OSSL_PARAM_BLD_push_octet_string) Call(p0 OSSL_PARAM_BLD_PTR, p1 *byte, p2 unsafe.Pointer, p3 int) int32

type _mkcgo_func_OSSL_PARAM_BLD_push_utf8_string uintptr

//cgo:funcptr
func (fp _mkcgo_func_OSSL_PARAM_BLD_push_utf8_string) Call(p0 OSSL_PARAM_BLD_PTR, p1 *byte, p2 *byte, p3 int) int32

type _mkcgo_func_OSSL_PARAM_BLD_to_param uintptr

//cgo:funcptr
func (fp _mkcgo_func_OSSL_PARAM_BLD_to_param) Call(p0 OSSL_PARAM_BLD_PTR) OSSL_PARAM_PTR

type _mkcgo_func_OSSL_PARAM_free uintptr

//cgo:funcptr
func (fp _mkcgo_func_OSSL_PARAM_free) Call(p0 OSSL_PARAM_PTR)

type _mkcgo_func_OSSL_PARAM_locate_const uintptr

//cgo:funcptr
func (fp _mkcgo_func_OSSL_PARAM_locate_const) Call(p0 OSSL_PARAM_PTR, p1 *byte) OSSL_PARAM_PTR

type _mkcgo_func_OSSL_PROVIDER_available uintptr

//cgo:funcptr
func (fp _mkcgo_func_OSSL_PROVIDER_available) Call(p0 OSSL_LIB_CTX_PTR, p1 *byte) int32

type _mkcgo_func_OSSL_PROVIDER_get0_name uintptr

//cgo:funcptr
func (fp _mkcgo_func_OSSL_PROVIDER_get0_name) Call(p0 OSSL_PROVIDER_PTR) *byte

type _mkcgo_func_OSSL_PROVIDER_try_load uintptr

//cgo:funcptr
func (fp _mkcgo_func_OSSL_PROVIDER_try_load) Call(p0 OSSL_LIB_CTX_PTR, p1 *byte, p2 int32) OSSL_PROVIDER_PTR

type _mkcgo_func_OpenSSL_version uintptr

//cgo:funcptr
func (fp _mkcgo_func_OpenSSL_version) Call(p0 int32) *byte

type _mkcgo_func_OpenSSL_version_num uintptr

//cgo:funcptr
func (fp _mkcgo_func_OpenSSL_version_num) Call() uint64

type _mkcgo_func_PKCS5_PBKDF2_HMAC uintptr

//cgo:funcptr
func (fp _mkcgo_func_PKCS5_PBKDF2_HMAC) Call(p0 *byte, p1 int32, p2 *byte, p3 int32, p4 int32, p5 EVP_MD_PTR, p6 int32, p7 *byte) int32

type _mkcgo_func_RAND_bytes uintptr

//cgo:funcptr
func (fp _mkcgo_func_RAND_bytes) Call(p0 *byte, p1 int32) int32

type _mkcgo_func_RAND_bytes_ex uintptr

//cgo:funcptr
func (fp _mkcgo_func_RAND_bytes_ex) Call(p0 OSSL_LIB_CTX_PTR, p1 *byte, p2 int, p3 uint32) int32

type _mkcgo_func_RSA_free uintptr

//cgo:funcptr
func (fp _mkcgo_func_RSA_free) Call(p0 RSA_PTR)

type _mkcgo_func_RSA_get0_crt_params uintptr

//cgo:funcptr
func (fp _mkcgo_func_RSA_get0_crt_params) Call(p0 RSA_PTR, p1 *BIGNUM_PTR, p2 *BIGNUM_PTR, p3 *BIGNUM_PTR)

type _mkcgo_func_RSA_get0_factors uintptr

//cgo:funcptr
func (fp _mkcgo_func_RSA_get0_factors) Call(p0 RSA_PTR, p1 *BIGNUM_PTR, p2 *BIGNUM_PTR)

type _mkcgo_func_RSA_get0_key uintptr

//cgo:funcptr
func (fp _mkcgo_func_RSA_get0_key) Call(p0 RSA_PTR, p1 *BIGNUM_PTR, p2 *BIGNUM_PTR, p3 *BIGNUM_PTR)

type _mkcgo_func_RSA_new uintptr

//cgo:funcptr
func (fp _mkcgo_func_RSA_new) Call() RSA_PTR

type _mkcgo_func_RSA_set0_crt_params uintptr

//cgo:funcptr
func (fp _mkcgo_func_RSA_set0_crt_params) Call(p0 RSA_PTR, p1 BIGNUM_PTR, p2 BIGNUM_PTR, p3 BIGNUM_PTR) int32

type _mkcgo_func_RSA_set0_factors uintptr

//cgo:funcptr
func (fp _mkcgo_func_RSA_set0_factors) Call(p0 RSA_PTR, p1 BIGNUM_PTR, p2 BIGNUM_PTR) int32

type _mkcgo_func_RSA_set0_key uintptr

//cgo:funcptr
func (fp _mkcgo_func_RSA_set0_key) Call(p0 RSA_PTR, p1 BIGNUM_PTR, p2 BIGNUM_PTR, p3 BIGNUM_PTR) int32
