// Code generated by 'go generate' with gen.go. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2022 The Ebitengine Authors

//go:build !cgo

#include "textflag.h"

TEXT ___errno_location(SB), NOSPLIT, $0-0
	BR purego___errno_location(SB)

TEXT _cgo_purego_setegid_trampoline(SB), NOSPLIT, $0
	MOVD R3, R3
	MOVD ·x_cgo_purego_setegid_call(SB), R12
	MOVD (R12), R12
	MOVD R12, CTR
	BR   (CTR)

TEXT _setegid(SB), NOSPLIT, $0-0
	BR purego_setegid(SB)

TEXT _cgo_purego_seteuid_trampoline(SB), NOSPLIT, $0
	MOVD R3, R3
	MOVD ·x_cgo_purego_seteuid_call(SB), R12
	MOVD (R12), R12
	MOVD R12, CTR
	BR   (CTR)

TEXT _seteuid(SB), NOSPLIT, $0-0
	BR purego_seteuid(SB)

TEXT _cgo_purego_setgid_trampoline(SB), NOSPLIT, $0
	MOVD R3, R3
	MOVD ·x_cgo_purego_setgid_call(SB), R12
	MOVD (R12), R12
	MOVD R12, CTR
	BR   (CTR)

TEXT _setgid(SB), NOSPLIT, $0-0
	BR purego_setgid(SB)

TEXT _cgo_purego_setregid_trampoline(SB), NOSPLIT, $0
	MOVD R3, R3
	MOVD ·x_cgo_purego_setregid_call(SB), R12
	MOVD (R12), R12
	MOVD R12, CTR
	BR   (CTR)

TEXT _setregid(SB), NOSPLIT, $0-0
	BR purego_setregid(SB)

TEXT _cgo_purego_setresgid_trampoline(SB), NOSPLIT, $0
	MOVD R3, R3
	MOVD ·x_cgo_purego_setresgid_call(SB), R12
	MOVD (R12), R12
	MOVD R12, CTR
	BR   (CTR)

TEXT _setresgid(SB), NOSPLIT, $0-0
	BR purego_setresgid(SB)

TEXT _cgo_purego_setresuid_trampoline(SB), NOSPLIT, $0
	MOVD R3, R3
	MOVD ·x_cgo_purego_setresuid_call(SB), R12
	MOVD (R12), R12
	MOVD R12, CTR
	BR   (CTR)

TEXT _setresuid(SB), NOSPLIT, $0-0
	BR purego_setresuid(SB)

TEXT _cgo_purego_setreuid_trampoline(SB), NOSPLIT, $0
	MOVD R3, R3
	MOVD ·x_cgo_purego_setreuid_call(SB), R12
	MOVD (R12), R12
	MOVD R12, CTR
	BR   (CTR)

TEXT _setreuid(SB), NOSPLIT, $0-0
	BR purego_setreuid(SB)

TEXT _cgo_purego_setuid_trampoline(SB), NOSPLIT, $0
	MOVD R3, R3
	MOVD ·x_cgo_purego_setuid_call(SB), R12
	MOVD (R12), R12
	MOVD R12, CTR
	BR   (CTR)

TEXT _setuid(SB), NOSPLIT, $0-0
	BR purego_setuid(SB)

TEXT _cgo_purego_setgroups_trampoline(SB), NOSPLIT, $0
	MOVD R3, R3
	MOVD ·x_cgo_purego_setgroups_call(SB), R12
	MOVD (R12), R12
	MOVD R12, CTR
	BR   (CTR)

TEXT _setgroups(SB), NOSPLIT, $0-0
	BR purego_setgroups(SB)
