// Code generated by 'go generate' with gen.go. DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2022 The Ebitengine Authors

//go:build go1.27 && !cgo

#include "textflag.h"

TEXT ___errno_location(SB), NOSPLIT, $0-0
	JMP purego___errno_location(SB)

TEXT _cgo_purego_setegid_trampoline(SB), NOSPLIT|NOFRAME, $0
	// R2 already has the argument from C caller
	MOVD ·x_cgo_purego_setegid_call(SB), R1
	MOVD (R1), R1
	BR   R1

TEXT _setegid(SB), NOSPLIT|NOFRAME, $0-0
	JMP purego_setegid(SB)

TEXT _cgo_purego_seteuid_trampoline(SB), NOSPLIT|NOFRAME, $0
	MOVD ·x_cgo_purego_seteuid_call(SB), R1
	MOVD (R1), R1
	BR   R1

TEXT _seteuid(SB), NOSPLIT|NOFRAME, $0-0
	JMP purego_seteuid(SB)

TEXT _cgo_purego_setgid_trampoline(SB), NOSPLIT|NOFRAME, $0
	MOVD ·x_cgo_purego_setgid_call(SB), R1
	MOVD (R1), R1
	BR   R1

TEXT _setgid(SB), NOSPLIT|NOFRAME, $0-0
	JMP purego_setgid(SB)

TEXT _cgo_purego_setregid_trampoline(SB), NOSPLIT|NOFRAME, $0
	// R2, R3 have arguments from C caller
	MOVD ·x_cgo_purego_setregid_call(SB), R1
	MOVD (R1), R1
	BR   R1

TEXT _setregid(SB), NOSPLIT|NOFRAME, $0-0
	JMP purego_setregid(SB)

TEXT _cgo_purego_setresgid_trampoline(SB), NOSPLIT|NOFRAME, $0
	// R2, R3, R4 have arguments from C caller
	MOVD ·x_cgo_purego_setresgid_call(SB), R1
	MOVD (R1), R1
	BR   R1

TEXT _setresgid(SB), NOSPLIT|NOFRAME, $0-0
	JMP purego_setresgid(SB)

TEXT _cgo_purego_setresuid_trampoline(SB), NOSPLIT|NOFRAME, $0
	// R2, R3, R4 have arguments from C caller
	MOVD ·x_cgo_purego_setresuid_call(SB), R1
	MOVD (R1), R1
	BR   R1

TEXT _setresuid(SB), NOSPLIT|NOFRAME, $0-0
	JMP purego_setresuid(SB)

TEXT _cgo_purego_setreuid_trampoline(SB), NOSPLIT|NOFRAME, $0
	// R2, R3 have arguments from C caller
	MOVD ·x_cgo_purego_setreuid_call(SB), R1
	MOVD (R1), R1
	BR   R1

TEXT _setreuid(SB), NOSPLIT|NOFRAME, $0-0
	JMP purego_setreuid(SB)

TEXT _cgo_purego_setuid_trampoline(SB), NOSPLIT|NOFRAME, $0
	MOVD ·x_cgo_purego_setuid_call(SB), R1
	MOVD (R1), R1
	BR   R1

TEXT _setuid(SB), NOSPLIT|NOFRAME, $0-0
	JMP purego_setuid(SB)

TEXT _cgo_purego_setgroups_trampoline(SB), NOSPLIT|NOFRAME, $0
	// R2, R3 have arguments from C caller
	MOVD ·x_cgo_purego_setgroups_call(SB), R1
	MOVD (R1), R1
	BR   R1

TEXT _setgroups(SB), NOSPLIT|NOFRAME, $0-0
	JMP purego_setgroups(SB)

