package main

import (
	"fmt"
	"io"
	"slices"
	"strconv"
	"strings"

	"github.com/golang-fips/openssl/v2/internal/mkcgo"
)

// generateGo output Go source file from src.
func generateGo(src *mkcgo.Source, w io.Writer) {
	// Output header notice and package declaration.
	fmt.Fprintf(w, "// Code generated by mkcgo. DO NOT EDIT.\n\n")
	fmt.Fprintf(w, "package %s\n\n", *packageName)

	// This block outputs C header includes and forward declarations for loader functions.
	fmt.Fprintf(w, "/*\n")
	fmt.Fprintf(w, "#cgo CFLAGS: -Wno-attributes\n")
	if *includeHeader != "" {
		fmt.Fprintf(w, "#include \"%s\"\n", *includeHeader)
	}
	for _, file := range src.Files {
		fmt.Fprintf(w, "#include %q\n", file)
	}
	for _, tag := range src.Tags() {
		fmt.Fprintf(w, "void __mkcgoLoad_%s(void* handle);\n", tag)
	}
	fmt.Fprintf(w, "*/\n")
	fmt.Fprintf(w, "import \"C\"\n")
	fmt.Fprintf(w, "import \"unsafe\"\n\n")

	// Generate Go enum values for C enums.
	generateGoEnums(src.Enums, w)

	// Generate type aliases for all
	generateGoAliases(src.Funcs, w)

	// Generate Go wrapper functions that load the C symbols.
	for _, tag := range src.Tags() {
		fmt.Fprintf(w, "func mkcgoLoad_%s(handle unsafe.Pointer) {\n", tag)
		fmt.Fprintf(w, "\tC.__mkcgoLoad_%s(handle)\n", tag)
		fmt.Fprintf(w, "}\n\n")
	}

	// Generate function wrappers.
	for _, fn := range src.Funcs {
		if fn.Variadic() {
			// cgo doesn't support variadic functions
			continue
		}
		generateGoFn(fn, w)
	}
}

// generateGoEnums generates Go enum values for C enums.
func generateGoEnums(enums []*mkcgo.Enum, w io.Writer) {
	if len(enums) == 0 {
		return
	}
	fmt.Fprintf(w, "const (\n")
	for _, enum := range enums {
		fmt.Fprintf(w, "\t%s = %s\n", enum.Name, enum.Value)
	}
	fmt.Fprintf(w, ")\n\n")
}

// generateGoAliases generates Go type aliases for C types.
func generateGoAliases(funcs []*mkcgo.Func, w io.Writer) {
	// Traverse all functions and collect the unique C types.
	ctypes := make(map[string]struct{})
	for _, fn := range funcs {
		handleType := func(typ string) {
			if typ == "" {
				return
			}
			typ = strings.TrimPrefix(typ, "const ")
			typ = strings.TrimRight(typ, "*")
			if _, ok := ctypes[typ]; ok {
				return
			}
			ctypes[typ] = struct{}{}
		}
		for _, p := range fn.Params {
			if p.Variadic() {
				continue
			}
			handleType(p.Type)
		}
		handleType(fn.Ret.Type)
	}
	types := make([]string, 0, len(ctypes))
	for typ := range ctypes {
		types = append(types, typ)
	}
	slices.Sort(types)
	for _, typ := range types {
		if isStdType(typ) {
			// Skip standard types.
			continue
		}
		fmt.Fprintf(w, "type %s = C.%s\n", typ, typ)
	}
}

// generateC creates the C source file content.
func generateC(src *mkcgo.Source, w io.Writer) {
	// Header and includes.
	fmt.Fprintf(w, "// Code generated by mkcgo. DO NOT EDIT.\n\n")
	if *includeHeader != "" {
		fmt.Fprintf(w, "#include \"%s\"\n", *includeHeader)
	}
	for _, file := range src.Files {
		fmt.Fprintf(w, "#include %q\n", file)
	}
	fmt.Fprintf(w, "#include <stddef.h>\n")
	fmt.Fprintf(w, "#include <stdlib.h>\n")
	fmt.Fprintf(w, "#include <stdint.h>\n")
	fmt.Fprintf(w, "#include <stdio.h>\n")
	fmt.Fprintf(w, "\n")

	// Platform-specific includes.
	fmt.Fprintf(w, "#ifdef _WIN32\n")
	fmt.Fprintf(w, "#include <windows.h>\n")
	fmt.Fprintf(w, "#define dlsym GetProcAddress\n")
	fmt.Fprintf(w, "#else\n")
	fmt.Fprintf(w, "#include <dlfcn.h>\n")
	fmt.Fprintf(w, "#endif\n\n")

	// Function pointer declarations.
	fmt.Fprintf(w, "#define __mkcgo__funcptr(name) typeof(name) *_g_##name;\n\n")
	for _, fn := range src.Funcs {
		if fn.VariadicInst {
			continue
		}
		fmt.Fprintf(w, "__mkcgo__funcptr(%s);\n", fn.ImportName)
	}
	fmt.Fprintf(w, "\n")

	fmt.Fprintf(w, "#define __mkcgo__dlsym(name) __mkcgo__dlsym2(name, name)\n\n")

	fmt.Fprintf(w, "#define __mkcgo__dlsym2(varname, funcname) \\\n")
	fmt.Fprintf(w, "\t_g_##varname = (typeof(_g_##varname))dlsym(handle, #funcname); \\\n")
	fmt.Fprintf(w, "\tif (_g_##varname == NULL) { \\\n")
	fmt.Fprintf(w, "\t\tfprintf(stderr, \"Cannot get required symbol \" #funcname \"\\n\"); \\\n")
	fmt.Fprintf(w, "\t\tabort(); \\\n")
	fmt.Fprintf(w, "\t}\n\n")

	// Loader functions for each tag.
	for _, tag := range src.Tags() {
		fmt.Fprintf(w, "void __mkcgoLoad_%s(void* handle) {\n", tag)
		for _, fn := range src.Funcs {
			if fn.VariadicInst {
				continue
			}
			if len(fn.Tags) == 0 && tag == "" {
				// Default tag.
				fmt.Fprintf(w, "\t__mkcgo__dlsym(%s)\n", fn.ImportName)
			} else {
				for _, tagAttr := range fn.Tags {
					if tagAttr.Tag == tag {
						if tagAttr.Name != "" {
							fmt.Fprintf(w, "\t__mkcgo__dlsym2(%s, %s)\n", fn.ImportName, tagAttr.Name)
						} else {
							fmt.Fprintf(w, "\t__mkcgo__dlsym(%s)\n", fn.ImportName)
						}
						break
					}
				}
			}
		}
		fmt.Fprintf(w, "}\n\n")
	}

	// Generate C function wrappers.
	for _, fn := range src.Funcs {
		if fn.Variadic() {
			// cgo doesn't support variadic functions
			continue
		}
		generateCFn(fn, w)
	}
}

// generateGoFn generates Go function f.
func generateGoFn(fn *mkcgo.Func, w io.Writer) {
	fmt.Fprintf(w, "func %s(%s)", fn.GoName, fnToGoParams(fn))
	if !retIsVoid(fn.Ret) {
		fmt.Fprintf(w, " %s ", cTypeToGo(fn.Ret.Type, false))
	}
	fmt.Fprintf(w, "{\n")
	fmt.Fprintf(w, "\t")
	var closePar int
	if !retIsVoid(fn.Ret) {
		fmt.Fprintf(w, "return ")
		goType := cTypeToGo(fn.Ret.Type, false)
		if goType != "" && goType != fn.Ret.Type {
			closePar++
			if goType[0] == '*' {
				goType = fmt.Sprintf("(%s)(unsafe.Pointer", goType)
				closePar++
			}
			fmt.Fprintf(w, "%s(", goType)
		}
	}
	fmt.Fprintf(w, "C.%s(%s)", fn.CName, fnToGoArgs(fn))
	if closePar > 0 {
		fmt.Fprint(w, strings.Repeat(")", closePar))
	}
	fmt.Fprintf(w, "\n")
	fmt.Fprintf(w, "}\n\n")
}

func generateCFn(fn *mkcgo.Func, w io.Writer) {
	fmt.Fprintf(w, "%s %s(%s) {\n\t", fn.Ret.Type, fn.CName, fnToCArgs(fn, true))
	if !retIsVoid(fn.Ret) {
		fmt.Fprintf(w, "return ")
	}
	fmt.Fprintf(w, "_g_%s(%s);\n", fn.ImportName, fnToCArgs(fn, false))
	fmt.Fprintf(w, "}\n\n")
}

// paramToGo converts C parameter p to Go parameter.
func paramToGo(p *mkcgo.Param) string {
	goType := cTypeToGo(p.Type, true)
	switch {
	case goType == "unsafe.Pointer" || goType == "":
		return p.Name
	case goType[0] == '*':
		return fmt.Sprintf("(%s)(unsafe.Pointer(%s))", goType, p.Name)
	}
	return fmt.Sprintf("%s(%s)", goType, p.Name)
}

// isStdType reports whether t is a standard C type.
func isStdType(t string) bool {
	_, found := cstdTypesToGo[t]
	return found
}

// cstdTypesToGo maps C standard types to Go types.
var cstdTypesToGo = map[string]string{
	"int8_t":             "int8",
	"uint8_t":            "uint8",
	"int16_t":            "int16",
	"uint16_t":           "uint16",
	"int32_t":            "int32",
	"uint32_t":           "uint32",
	"int64_t":            "int64",
	"uint64_t":           "uint64",
	"int":                "int32",
	"unsigned int":       "uint32",
	"long":               "int32",
	"unsigned long":      "uint32",
	"long long":          "int64",
	"unsigned long long": "uint64",
	"size_t":             "int",
	"uintptr_t":          "uintptr",
	"char":               "byte",
	"unsigned char":      "byte",
	"signed char":        "int8",
	"void":               "",
}

// cstdTypesToCgo maps C standard types to special cgo types.
// Most C don't need any special handling, only the ones that have spaces.
var cstdTypesToCgo = map[string]string{
	"signed char":        "schar",
	"unsigned char":      "uchar",
	"unsigned short":     "ushort",
	"unsigned int":       "uint",
	"unsigned long":      "ulong",
	"long long":          "longlong",
	"unsigned long long": "ulonglong",
}

// cTypeToGo converts C type t to a Go type.
func cTypeToGo(t string, cgo bool) string {
	t, _ = strings.CutPrefix(t, "const ")
	if t == "void" {
		return ""
	}
	if strings.HasPrefix(t, "void*") {
		return "unsafe.Pointer"
	}
	if strings.HasSuffix(t, "*") {
		// Remove all trailing '*' characters.
		var i, n int
		for i = len(t) - 1; i >= 0; i-- {
			if t[i] != '*' {
				break
			}
			n++
		}
		s := cTypeToGo(t[:i+1], cgo)
		if s != "" {
			s = strings.Repeat("*", n) + s
		}
		return s
	}
	if !isStdType(t) {
		if cgo {
			// Non-standard C types are aliased so C.<type> so they don't need to be converted.
			return ""
		}
		return t
	}
	if cgo {
		if s, ok := cstdTypesToCgo[t]; ok {
			t = s
		}
		return "C." + t
	}
	if t, ok := cstdTypesToGo[t]; ok {
		return t
	}
	return t
}

// paramToC returns C source code of parameter p.
func paramToC(i int, p *mkcgo.Param, addType bool) string {
	var s string
	if addType {
		s += p.Type
	}
	if p.Type != "void" && p.Type != "..." {
		if len(s) > 0 {
			s += " "
		}
		s += "_arg" + strconv.Itoa(i)
	}
	return s
}

func retIsVoid(r *mkcgo.Return) bool {
	return r.Type == "void"
}

// fnToGoParams returns source code for function f parameters.
func fnToGoParams(fn *mkcgo.Func) string {
	return join(fn.Params, func(_ int, p *mkcgo.Param) string {
		return p.Name + " " + cTypeToGo(p.Type, false)
	}, ", ")
}

// argList returns source code for C parameters for function f.
func fnToGoArgs(fn *mkcgo.Func) string {
	return join(fn.Params, func(_ int, p *mkcgo.Param) string {
		return paramToGo(p)
	}, ", ")
}

// fnToCArgs returns source code for C parameters for function f.
func fnToCArgs(fn *mkcgo.Func, addType bool) string {
	return join(fn.Params, func(i int, p *mkcgo.Param) string {
		return paramToC(i, p, addType)
	}, ", ")
}

// join concatenates parameters ps into a string with sep separator.
// Each parameter is converted into string by applying fn to it
// before conversion.
func join(ps []*mkcgo.Param, fn func(int, *mkcgo.Param) string, sep string) string {
	if len(ps) == 0 {
		return ""
	}
	params := make([]string, 0, len(ps))
	for i, p := range ps {
		param := fn(i, p)
		if param != "" {
			params = append(params, param)
		}
	}
	return strings.Join(params, sep)
}
