package main

import (
	"bytes"
	"cmp"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"slices"
	"strings"

	"github.com/golang-fips/openssl/v2/internal/mkcgo"
)

var (
	fileName      = flag.String("out", "", "output file name (standard output if omitted)")
	includeHeader = flag.String("include", "", "include header file")
	packageName   = flag.String("package", "", "package name")
	nocgo         = flag.Bool("nocgo", false, "don't use cgo")
	mode          = flag.String("mode", "dynamic", "symbol load mode: dynamic, dynload")
	private       = flag.Bool("private", false, "all Go generated symbols are kept unexported")
	noerrors      = flag.Bool("noerrors", false, "disable error handling")
	extratags     = flag.String("tags", "", "tags to add to the generated files")
	copyrightFile = flag.String("copyright", "", "file containing copyright notice to add to the generated files")
)

var copyright []byte

func usage() {
	fmt.Fprintf(os.Stderr, "usage: mkcgo [flags] [path ...]\n")
	flag.PrintDefaults()
	fmt.Fprintf(os.Stderr, "\n")
	os.Exit(1)
}

func dynamic() bool {
	return *mode == "dynamic"
}

func dynload() bool {
	return *mode == "dynload"
}

func main() {
	// Set up and parse flags.
	flag.Usage = usage
	flag.Parse()
	if len(flag.Args()) == 0 {
		fmt.Fprintln(os.Stderr, "no files to parse provided")
		usage()
	}

	if *extratags != "" && strings.Contains(*extratags, " ") {
		*extratags = "(" + *extratags + ")"
	}

	if *copyrightFile != "" {
		var err error
		copyright, err = os.ReadFile(*copyrightFile)
		if err != nil {
			log.Fatalf("failed to read copyright file: %v", err)
		}
	}

	var src mkcgo.Source
	// Parse source files.
	for _, arg := range flag.Args() {
		file, err := os.Open(arg)
		if err != nil {
			log.Fatal(err)
		}
		err = src.Parse(file)
		file.Close()
		if err != nil {
			log.Fatal(err)
		}
	}

	// Sort functions by name to get deterministic output
	// even when the order of the functions in the source file changes.
	slices.SortFunc(src.Funcs, func(a, b *mkcgo.Func) int {
		return cmp.Compare(a.Name, b.Name)
	})

	type outFile struct {
		suffix string
		data   []byte
	}
	var outFiles []outFile

	if *nocgo {
		// Generate nocgo mode files
		var nocgoGoBuffer, assemblyBuffer bytes.Buffer
		generateGoNocgo(&src, &nocgoGoBuffer)
		outFiles = append(outFiles, outFile{"_nocgo.go", nocgoGoBuffer.Bytes()})

		if dynamic() {
			generateAssembly(&src, &assemblyBuffer)
			outFiles = append(outFiles, outFile{".s", assemblyBuffer.Bytes()})
		}
	} else {
		var gobuf, go124buf, hbuf, cbuf bytes.Buffer
		generateGoCgo(&src, &gobuf)
		generateGo124(&src, &go124buf)
		generateCHeader(&src, &hbuf)
		generateC(&src, &cbuf)

		outFiles = append(outFiles, outFile{"_cgo.go", gobuf.Bytes()})
		outFiles = append(outFiles, outFile{"_cgo_go124.go", go124buf.Bytes()})
		outFiles = append(outFiles, outFile{".h", hbuf.Bytes()})
		outFiles = append(outFiles, outFile{".c", cbuf.Bytes()})
	}

	var commonGoBuffer bytes.Buffer
	generateGoCommon(&src, &commonGoBuffer)
	outFiles = append(outFiles, outFile{".go", commonGoBuffer.Bytes()})

	for _, f := range outFiles {
		data := f.data
		if len(data) == 0 {
			continue
		}
		name := autogeneratedFileName(f.suffix)
		if strings.HasSuffix(name, ".go") {
			data = goformat(data)
		}
		var err error
		if *fileName == "" {
			// Write output. If no explicit output file is specified,
			// // write both Go and C output to stdout.
			os.Stdout.WriteString("// === " + name + " ===\n\n")
			_, err = os.Stdout.Write(data)
		} else {
			err = os.WriteFile(name, data, 0o644)
		}
		if err != nil {
			log.Fatal(err)
		}
	}
}

// autogeneratedFileName returns the name of the autogenerated file
// using the provided suffix.
func autogeneratedFileName(suffix string) string {
	var baseName string
	if *fileName == "" {
		baseName = "mkcgo"
	} else {
		baseName = strings.TrimSuffix(*fileName, ".go")
	}
	return baseName + suffix
}

func writeTempSourceFile(data []byte) (string, error) {
	f, err := os.CreateTemp("", "mkcgo-generated-*.go")
	if err != nil {
		return "", err
	}
	_, err = f.Write(data)
	if closeErr := f.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		os.Remove(f.Name()) // best effort
		return "", err
	}
	return f.Name(), nil
}

func goformat(data []byte) []byte {
	fdata, err := format.Source(data)
	if err != nil {
		log.Printf("failed to format source: %v", err)
		f, err := writeTempSourceFile(data)
		if err != nil {
			log.Fatalf("failed to write unformatted source to file: %v", err)
		}
		log.Fatalf("for diagnosis, wrote unformatted source to %v", f)
	}
	return fdata
}
