# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Check Vendored Imports
permissions:
   contents: read
jobs:
  check-imports:
    # Verify that packages vendored into Go's standard library only use
    # allowed stdlib imports. New imports require a matching update to the
    # deps_test.go patch in microsoft-go.
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version: 1.26
        go-download-base-url: "https://aka.ms/golang/release/latest"

    - name: Check vendored package imports
      run: |
        go run github.com/microsoft/go-infra/cmd/check-imports@v0.0.12 \
          -pkg ./internal/fakecgo \
          -allow '' \
          -pkg ./internal/ossl \
          -allow errors,unsafe \
          -pkg ./osslsetup \
          -allow errors,strconv,sync,syscall,unsafe \
          -pkg ./openssl
