on:
  push:
    branches:
      - v2
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.24.x, 1.25.x]
        openssl-version: [1.1.0, 1.1.1, 3.0.1, 3.0.13, 3.1.5, 3.2.1, 3.3.0, 3.3.1, 3.4.0, 3.5.0]
        host: [ubuntu-22.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.host }}
    steps:
    - name: Install build tools
      run: sudo apt-get install -y build-essential
    - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Verify go generate leaves no changes
      run: |
        go generate ./...
        git diff --exit-code
    - name: Install OpenSSL
      run: sudo sh ./scripts/openssl.sh ${{ matrix.openssl-version }}
    - name: Check headers
      working-directory: ./cmd/checkheader
      run: |
        go run . -include /usr/local/src/openssl-${{ matrix.openssl-version }}/include -shim ../../internal/ossl/shims.h
    - name: Set OpenSSL config and prove FIPS
      run: |
        sudo cp ./scripts/openssl-3.cnf /usr/local/ssl/openssl.cnf
        go test -v -count 0 . | grep -q "FIPS enabled: true"
      if: ${{ matrix.openssl-version == '3.0.1' }}
      env:
        GO_OPENSSL_VERSION_OVERRIDE: ${{ matrix.openssl-version }}
    - name: Run Test
      # Run each test 10 times so the garbage collector chimes in
      # and exercises the multiple finalizers we use.
      # This can detect use-after-free and double-free issues.
      run: go test -shuffle=on -gcflags=all=-d=checkptr -count 10 -v ./...
      env:
        GO_OPENSSL_VERSION_OVERRIDE: ${{ matrix.openssl-version }}
        CGO_ENABLED: 1
    - name: Run Test CGO disabled
      run: go test -shuffle=on -count 10 -v ./...
      env:
        GO_OPENSSL_VERSION_OVERRIDE: ${{ matrix.openssl-version }}
        CGO_ENABLED: 0
        GOFLAGS: -tags=goexperiment.ms_nocgo_opensslcrypto
    - name: Run Test CGO disabled and optimizations off
      run: go test -shuffle=on -count 10 -gcflags=all="-N -l" -v ./...
      env:
        GO_OPENSSL_VERSION_OVERRIDE: ${{ matrix.openssl-version }}
        CGO_ENABLED: 0
        GOFLAGS: -tags=goexperiment.ms_nocgo_opensslcrypto,noopt
    - name: Run Test with address sanitizer
      if: ${{ runner.arch == 'X64' }} # arm64 thread sanitizer is flaky, unrelated to this codebase
      run: |
        ok=true
        for t in $(go test ./... -list=. | grep '^Test'); do
          go test ./... -gcflags=all=-d=checkptr -asan -run ^$t$ -v || ok=false
        done
        $ok
      env:
        GO_OPENSSL_VERSION_OVERRIDE: ${{ matrix.openssl-version }}

  ossltest:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.24.x, 1.25.x]
        host: [
          # the non-intel macOS runners use ARM64
          {os: macos-15-intel, openssl-version: /usr/local/opt/openssl@3/lib/libcrypto.3.dylib},
          {os: macos-15, openssl-version: /opt/homebrew/opt/openssl@3/lib/libcrypto.3.dylib},
          {os: windows-2022, openssl-version: libcrypto-3-x64.dll}
        ]
    runs-on: ${{ matrix.host.os }}
    steps:
    - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Run Test
      run: go test -shuffle=on -gcflags=all=-d=checkptr -count 10 -v ./...
      env:
        GO_OPENSSL_VERSION_OVERRIDE: ${{ matrix.host.openssl-version }}
        CGO_ENABLED: 1
    - name: Run Test CGO disabled
      run: go test -shuffle=on -count 10 -v ./...
      env:
        GO_OPENSSL_VERSION_OVERRIDE: ${{ matrix.host.openssl-version }}
        CGO_ENABLED: 0
        GOFLAGS: -tags=goexperiment.ms_nocgo_opensslcrypto

  container:
    strategy:
      fail-fast: false
      matrix:
        image: [mcr.microsoft.com/oss/go/microsoft/golang:1.24-azurelinux3.0, mcr.microsoft.com/oss/go/microsoft/golang:1.24-cbl-mariner2.0]
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Run Test
      run: go test -shuffle=on -v ./...
      env:
        CGO_ENABLED: 1
    - name: Run Test CGO disabled
      run: go test -shuffle=on -v ./...
      env:
        CGO_ENABLED: 0
        GOFLAGS: -tags=goexperiment.ms_nocgo_opensslcrypto

  test-qemu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.24, 1.25]
        architecture: [ppc64le, s390x, riscv64]
    steps:
    - uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      with:
        platforms: ${{ matrix.architecture }}
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Run tests on ${{matrix.architecture}}
      run: |
        docker run --rm --platform linux/${{matrix.architecture}} \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          golang:${{ matrix.go-version }} \
          bash -c "
            go test -shuffle=on -v ./...
          "

  # Verify that golang-fips/openssl builds successfully without cgo enabled.
  #
  # A project can avoid attempting to build the openssl package by only
  # importing it from Go files with a cgo build tag. However, this isn't always
  # reasonable. In that case, we can help by making sure the openssl package
  # builds successfully even without cgo.
  #
  # For example, the Microsoft build of Go compiles this module without cgo when
  # running a cross-platform build.
  #
  # The golang-fips/openssl module can't do any crypto when built without cgo,
  # but it exports a few simple functions and types.
  cgolessbuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Run Build
      run: CGO_ENABLED=0 go build ./...

  conclusion:
    needs: [test, ossltest, container, test-qemu, cgolessbuild]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Result
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" || "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo "One or more jobs failed or were cancelled."
            exit 1
          fi
          echo "All jobs passed."
